import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const A_JUICE_POINT_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'a-juice-point-merida',
  name: 'A Juice Point',
  tagline: 'Jugos, sándwiches y desayunos saludables',
  category: 'cafe',
  concept: 'Barra casual de desayunos y brunch en Mérida con jugos naturales, combos, sándwiches de pan de doce granos, ensaladas, licuados y café.',
  identity: {
    id: 'a-juice-point-merida',
    name: 'A Juice Point',
    tagline: 'Jugos, sándwiches y desayunos saludables',
    category: 'cafe',
    concept: 'Barra casual de desayunos y brunch en Mérida con jugos naturales, combos, sándwiches de pan de doce granos, ensaladas, licuados y café.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.6 0.16 139)',
    accentColor: 'oklch(0.82 0.17 88)',
    bgBase: 'oklch(0.99 0.012 115)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.6 0.16 139)',
    primaryHover: 'oklch(0.5 0.15 139)',
    accent: 'oklch(0.82 0.17 88)',
    cta: 'oklch(0.63 0.18 45)',
    background: 'oklch(0.99 0.012 115)',
    surface: 'oklch(0.998 0.004 115)',
    surfaceAlt: 'oklch(0.95 0.032 125)',
    border: 'oklch(0.86 0.035 125)',
    text: 'oklch(0.22 0.038 138)',
    textMuted: 'oklch(0.42 0.035 138)',
    radius: 'soft',
  },
  seo: {
    title: 'A Juice Point Mérida - Jugos y desayunos',
    description: 'A Juice Point en Mérida: jugos naturales, combos de desayuno, sándwiches, ensaladas, licuados y café.',
    keywords: ['a juice point', 'jugos mérida', 'desayunos mérida', 'sándwiches mérida', 'brunch saludable mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'A Juice Point\nenergía fresca en Mérida',
    subheadline: 'Jugos combinados, sándwiches, ensaladas y café para desayunar ligero, rápido y con intención.',
    ctaLabel: 'Ver menú',
    ctaSecondaryLabel: 'Ubicación',
    locationLabel: 'Miguel Alemán, Mérida',
    backgroundImage: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.24,
  },
  cta: {
    reservationLabel: 'Pedir info',
    whatsappLabel: 'Escribir',
    stickyLabel: 'Menú',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Jugos naturales y fruta fresca en barra',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Fresco y directo',
      heading: 'Un menú saludable que se entiende en segundos',
      lead: 'Los listados públicos muestran una oferta clara: combos con jugos, sándwiches, ensaladas, licuados, fruta, aguas y bebidas calientes.',
      body: 'El diseño aprovecha esa claridad con categorías visuales, colores frescos y CTAs de pedido para que el visitante no tenga que navegar redes antes de decidir.',
      foundedLabel: 'Miguel Alemán',
    },
    menuHighlights: {
      eyebrow: 'Favoritos del menú',
      heading: 'Combos, sándwiches y jugos combinados',
      subheading: 'Una carta organizada alrededor de desayunos rápidos, ingredientes frescos y bebidas fáciles de pedir.',
      fullMenuLabel: 'Explorar menú',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Un concepto fácil de vender desde móvil',
      subheading: 'La presencia en delivery ya valida categorías, precios y hábitos de pedido.',
      proofItems: [
        { value: '4.6', label: 'Rating delivery' },
        { value: '7:00', label: 'Apertura publicada' },
        { value: '12', label: 'Categorías de menú' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Encuentra A Juice Point en Miguel Alemán',
    },
    menuPage: {
      eyebrow: 'Desayunos + jugos',
      heading: 'Menú A Juice Point',
      lead: 'Combos, sándwiches de pan de doce granos, ensaladas, jugos combinados, licuados y bebidas calientes.',
      finalHeading: '¿Listo para pedir A Juice Point?',
      finalDescription: 'El menú y el contacto quedan a un toque para resolver rápido.',
    },
  },
  menuCategories: [
    { id: 'combos', name: 'Combos', description: 'Sándwich más jugo combinado' },
    { id: 'sandwiches', name: 'Sándwiches', description: 'Pan de doce granos y aderezo JP' },
    { id: 'jugos', name: 'Jugos', description: 'Verdes, energéticos y antigripales' },
    { id: 'ensaladas', name: 'Ensaladas', description: 'Opciones frescas con fruta y panela' },
    { id: 'bebidas', name: 'Bebidas', description: 'Licuados, café y aguas' },
  ],
  menuItems: [
    { id: 'ajp1', categoryId: 'combos', name: 'Combo Vegetariano', description: 'Sándwich vegetariano con jugo verde de medio litro.', price: '$155', tag: 'popular', featured: true },
    { id: 'ajp2', categoryId: 'combos', name: 'Combo Light', description: 'Sándwich de queso y germinado con jugo quema grasa.', price: '$155', featured: true },
    { id: 'ajp3', categoryId: 'combos', name: 'Vitamina C', description: 'Sándwich de pavo con jugo antigripal de naranja, guayaba, apio, limón y miel.', price: '$155', tag: 'signature', featured: true },
    { id: 'ajp4', categoryId: 'sandwiches', name: 'Sándwich de pollo', description: 'Pan de doce granos, pollo, apio, mayonesa, lechuga, jitomate y aderezo JP.', price: '$120' },
    { id: 'ajp5', categoryId: 'sandwiches', name: 'Sándwich vegetariano', description: 'Zanahoria, betabel, aguacate, lechuga, jitomate y aderezo JP.', price: '$105' },
    { id: 'ajp6', categoryId: 'jugos', name: 'Jugo verde', description: 'Naranja, toronja, piña, nopal, apio y perejil.', price: '$70', featured: true },
    { id: 'ajp7', categoryId: 'jugos', name: 'Jugo energético', description: 'Naranja, piña y fresa.', price: '$70' },
    { id: 'ajp8', categoryId: 'ensaladas', name: 'Ensalada de arándano', description: 'Lechuga, espinaca, zanahoria, queso panela, arándano, naranja y aderezo JP.', price: '$92' },
    { id: 'ajp9', categoryId: 'bebidas', name: 'Licuado de fresa', description: 'Licuado con leche deslactosada.', price: '$63' },
    { id: 'ajp10', categoryId: 'bebidas', name: 'Café americano', description: 'Café de grano molido.', price: '$53' },
  ],
  promotions: [
    { id: 'ajpp1', title: 'Combo de mañana', description: 'Sándwich más jugo para una decisión de desayuno sin fricción.', badge: 'Combo', ctaLabel: 'Ver menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'ajpp2', title: 'Jugos combinados', description: 'Una categoría perfecta para mostrar colores, ingredientes y beneficios.', badge: 'Fresco', ctaLabel: 'Escribir', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'ajpt1', name: 'Cliente delivery', source: 'Direct', rating: 5, text: 'La carta pública facilita elegir combos, jugos y sándwiches desde móvil.', date: '2026' },
    { id: 'ajpt2', name: 'Cliente local', source: 'Google', rating: 5, text: 'Un concepto fresco para desayunar rápido en Mérida.', date: '2026' },
    { id: 'ajpt3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Jugos, desayunos y opciones saludables con una identidad clara.', date: '2026' },
  ],
  faqs: [
    { question: '¿Qué vende A Juice Point?', answer: 'Jugos naturales, combos, sándwiches, ensaladas, licuados, fruta, café y aguas.' },
    { question: '¿Dónde está la sucursal Miguel Alemán?', answer: 'En Calle 27, Miguel Alemán, Mérida, Yucatán, con referencia pública en plataformas de delivery.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rápido A Juice Point',
    messageTemplate: 'Hola A Juice Point. Quisiera información sobre menú o pedido para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529999083820',
  },
  whatsapp: {
    number: '529999083820',
    defaultMessage: 'Hola A Juice Point, quisiera información sobre menú, pedidos u horarios.',
    floatingButton: true,
    ariaLabel: 'Contactar a A Juice Point por WhatsApp',
  },
  location: {
    address: 'Calle 27, Miguel Alemán',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97148',
    country: 'México',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=A%20Juice%20Point%20Calle%2027%20Miguel%20Aleman%20Merida',
    mapAriaLabel: 'Mapa de ubicación de A Juice Point en Mérida',
    mapImageAlt: 'Mapa referencial de A Juice Point en Mérida',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '7:00 am - 2:15 pm' },
      { day: 'Martes', hours: '7:00 am - 2:15 pm' },
      { day: 'Miércoles', hours: '7:00 am - 2:15 pm' },
      { day: 'Jueves', hours: '7:00 am - 2:15 pm' },
      { day: 'Viernes', hours: '7:00 am - 2:10 pm' },
      { day: 'Sábado', hours: '8:00 am - 11:45 am' },
      { day: 'Domingo', hours: 'Cerrado', closed: true },
    ],
    phone: '+52 999 908 3820',
    email: 'contacto@ajuicepoint.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/ajuicepoint/',
  },
};
