import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const CALABAZO_RESTAURANTE_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'calabazo-restaurante',
  name: 'Calabazo',
  tagline: 'Cocina local intima en Hotel Sutuk',
  category: 'restaurant',
  concept: 'Restaurante boutique de 30 asientos dentro de Hotel Sutuk, con cocina local contemporanea, producto regional y enfoque farm to table.',
  identity: {
    id: 'calabazo-restaurante',
    name: 'Calabazo',
    tagline: 'Cocina local intima en Hotel Sutuk',
    category: 'restaurant',
    concept: 'Restaurante boutique de 30 asientos dentro de Hotel Sutuk, con cocina local contemporanea, producto regional y enfoque farm to table.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.33 0.07 108)',
    accentColor: 'oklch(0.56 0.09 58)',
    bgBase: 'oklch(0.976 0.018 88)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.33 0.07 108)',
    primaryHover: 'oklch(0.33 0.07 108)',
    accent: 'oklch(0.56 0.09 58)',
    cta: 'oklch(0.73 0.1 82)',
    background: 'oklch(0.976 0.018 88)',
    surface: 'oklch(0.997 0.006 88)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.2 0.035 92)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Calabazo - Cocina local intima en Hotel Sutuk',
    description: 'Calabazo: Restaurante boutique de 30 asientos dentro de Hotel Sutuk, con cocina local contemporanea, producto regional y enfoque farm to table.',
    keywords: ['Calabazo', 'Cocina local intima en Hotel Sutuk', 'Hotel Sutuk, Valladolid', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Calabazo\n30 asientos de temporada',
    subheadline: 'Una presencia independiente para que una cocina intima no viva escondida dentro del hotel: menu, reservas y relato propio.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Hotel Sutuk, Valladolid',
    backgroundImage: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Calabazo - Hotel Sutuk, Valladolid',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Calabazo ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Calabazo',
      lead: 'Calabazo parece pequeno por eleccion: 30 lugares, ingredientes regionales y una experiencia boutique.',
      body: 'El sitio debe separar el restaurante del hotel sin romper la relacion: hacerlo encontrable, reservar facil y comunicar cocina de temporada con precision.',
      foundedLabel: 'Hotel Sutuk, Valladolid',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Cocina local intima en Hotel Sutuk',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '30', label: 'Asientos' },
        { value: 'Hotel Sutuk', label: 'Ubicacion boutique' },
        { value: 'Farm', label: 'Producto regional' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Calabazo en Hotel Sutuk, Valladolid',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Calabazo',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Calabazo?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'temporada', name: 'Temporada', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'entradas', name: 'Entradas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'platos-fuertes', name: 'Platos fuertes', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'vegetal', name: 'Vegetal', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'bebidas', name: 'Bebidas', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'temporada', name: 'Ensalada de milpa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'entradas', name: 'Tostada de temporada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'platos-fuertes', name: 'Calabaza rostizada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'vegetal', name: 'Pesca local', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'bebidas', name: 'Pollo de rancho', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'temporada', name: 'Arroz con vegetales', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'entradas', name: 'Postre de cacao', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm8', categoryId: 'platos-fuertes', name: 'Agua de temporada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' }
  ],
  promotions: [
    { id: 'p1', title: 'Mesa intima de 30 asientos', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Producto regional', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1800&auto=format&fit=crop&q=85', alt: 'Calabazo preview image 1', caption: 'Calabazo', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1000&auto=format&fit=crop&q=85', alt: 'Calabazo preview image 2', caption: 'Calabazo', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1600&auto=format&fit=crop&q=85', alt: 'Calabazo preview image 3', caption: 'Calabazo', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80', alt: 'Calabazo preview image 4', caption: 'Calabazo', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=1800&auto=format&fit=crop&q=85', alt: 'Calabazo preview image 5', caption: 'Calabazo', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1000&auto=format&fit=crop&q=85', alt: 'Calabazo preview image 6', caption: 'Calabazo', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 1.8k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Calabazo?', answer: 'Restaurante boutique de 30 asientos dentro de Hotel Sutuk, con cocina local contemporanea, producto regional y enfoque farm to table.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Calabazo',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Calabazo. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529850000000',
  },
  whatsapp: {
    number: '529850000000',
    defaultMessage: 'Hola Calabazo, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Calabazo por WhatsApp',
  },
  location: {
    address: 'Hotel Sutuk, Valladolid',
    city: 'Hotel Sutuk',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Calabazo%20Hotel%20Sutuk%2C%20Valladolid',
    mapAriaLabel: 'Mapa de ubicacion de Calabazo',
    mapImageAlt: 'Mapa referencial de Calabazo',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 985 000 0000',
    email: 'reservas@calabazorestaurante.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/calabazorestaurante/',
  },
};

