import { BusinessConfig } from '../business.config';
import { DEFAULT_RESTAURANT_PRESET } from '../presets/default-restaurant.preset';

export const COFFEE_ST_FITZ_CONFIG: BusinessConfig = {
  ...(DEFAULT_RESTAURANT_PRESET as BusinessConfig),
  id: 'coffee-st-fitz-merida',
  name: 'Coffee St Fitz',
  tagline: 'Desayunos, café y pan del día',
  category: 'cafe',
  concept: 'Café luminoso de desayunos en Mérida, enfocado en resolver rápido menú, horario, ubicación y contacto desde móvil.',
  identity: {
    id: 'coffee-st-fitz-merida',
    name: 'Coffee St Fitz',
    tagline: 'Desayunos, café y pan del día',
    category: 'cafe',
    concept: 'Café luminoso de desayunos en Mérida, enfocado en resolver rápido menú, horario, ubicación y contacto desde móvil.',
  },
  brand: {
    primaryColor: 'oklch(0.56 0.12 55)',
    accentColor: 'oklch(0.67 0.11 95)',
    bgBase: 'oklch(0.98 0.012 90)',
    fontDisplay: 'Cormorant Garamond',
    fontBody: 'Inter',
    darkMode: false,
  },
  theme: {
    mode: 'light',
    primary: 'oklch(0.56 0.12 55)',
    primaryHover: 'oklch(0.48 0.12 55)',
    accent: 'oklch(0.66 0.11 95)',
    cta: 'oklch(0.52 0.16 38)',
    background: 'oklch(0.98 0.012 90)',
    surface: 'oklch(0.995 0.006 90)',
    surfaceAlt: 'oklch(0.955 0.018 88)',
    border: 'oklch(0.84 0.018 80)',
    text: 'oklch(0.24 0.028 62)',
    textMuted: 'oklch(0.44 0.026 62)',
    textInverse: 'oklch(0.99 0.006 90)',
    fontDisplay: 'Cormorant Garamond',
    fontBody: 'Inter',
    radius: 'soft',
    shadow: 'medium',
    motionIntensity: 'standard',
  },
  sections: [
    { id: 'hero', enabled: true, variant: 'editorial' },
    { id: 'concept', enabled: true, variant: 'default' },
    { id: 'menu-highlights', enabled: true, variant: 'default' },
    { id: 'promotions', enabled: true, variant: 'compact' },
    { id: 'gallery', enabled: true, variant: 'editorial' },
    { id: 'testimonials', enabled: true, variant: 'compact' },
    { id: 'branches', enabled: false },
    { id: 'location', enabled: true, variant: 'default' },
  ],
  seo: {
    title: 'Coffee St Fitz Mérida - Cafetería y desayunos',
    description: 'Coffee St Fitz Mérida: desayunos, café, pan del día, jugos, smoothies y brunch casual en Mérida, Yucatán.',
    keywords: ['coffee st fitz', 'cafetería mérida', 'desayunos mérida', 'brunch mérida', 'café mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    headline: 'Coffee St Fitz\npara tus mañanas en Mérida',
    subheadline: 'Desayunos, jugos, cafés y pan recién horneado en una experiencia clara, cálida y lista para visitar.',
    ctaLabel: 'Explorar menú',
    ctaSecondaryLabel: 'Ver ubicación',
    locationLabel: 'Mérida, Yucatán',
    scrollCueLabel: 'Explorar',
    backgroundImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.35,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escríbenos',
    stickyLabel: 'Menú',
  },
  navigation: {
    homeLabel: 'Inicio',
    menuLabel: 'Menú',
    aboutLabel: 'Concepto',
    contactLabel: 'Contacto',
  },
  footer: {
    copyrightLabel: 'Coffee St Fitz - Mérida, Yucatán',
    navigationHeading: 'Navegación',
    hoursHeading: 'Horarios',
    contactHeading: 'Contacto',
  },
  sectionCopy: {
    images: {
      heroBackground: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Barra de café cálida con tazas y pan de desayuno',
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {
        m1: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
        m2: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&auto=format&fit=crop&q=80',
        m3: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
        m4: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&auto=format&fit=crop&q=80',
        m5: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&auto=format&fit=crop&q=80',
        m6: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
        m7: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
        m8: 'https://images.unsplash.com/photo-1513442542250-854d436a73f2?w=600&auto=format&fit=crop&q=80',
        m9: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80',
        m10: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
        m11: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=600&auto=format&fit=crop&q=80',
        m12: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=600&auto=format&fit=crop&q=80',
      },
    },
    concept: {
      eyebrow: 'El concepto',
      heading: 'Un café pensado para convertir mejor que redes sociales',
      lead: 'La marca comunica desayunos, café, pan del día, fruta, jugos, smoothies, chapatas, omelettes y crepas; el sitio ordena esa energía en una experiencia más clara y vendible.',
      body: 'El sistema prioriza lo que un visitante móvil necesita decidir en segundos: qué se sirve, cómo se ve, a qué hora abre, dónde está y cómo contactar.',
      foundedLabel: 'Sucursal Mérida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos del menú',
      heading: 'Desayunos, café y antojos de mañana',
      subheading: 'Una muestra breve para provocar visita rápida: platos completos, opciones dulces, café y bebidas frescas.',
      fullMenuLabel: 'Explorar menú',
    },
    promotions: {
      eyebrow: 'Momentos para volver',
      heading: 'Promociones y antojos fáciles de vender',
      validUntilPrefix: 'Disponible hasta',
    },
    gallery: {
      eyebrow: 'Así se vive',
      heading: 'Café, desayuno y una mañana bien resuelta',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Desayunos' },
        { id: 'drinks', label: 'Café y bebidas' },
        { id: 'interior', label: 'Espacio' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Señales que ayudan a decidir',
      subheading: 'El sitio convierte interés disperso en redes y mapas en acciones concretas: menú, mapa y contacto.',
      proofItems: [
        { value: '7:30', label: 'Apertura publicada' },
        { value: '999', label: 'Contacto local visible' },
        { value: '1', label: 'Sucursal enfocada' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Encuentra Coffee St Fitz en Mérida',
    },
    menuPage: {
      eyebrow: 'Café + desayuno',
      heading: 'Menú Coffee St Fitz',
      lead: 'Desayunos, café y opciones casuales para una decisión rápida desde móvil.',
      finalHeading: 'Listo para visitar Coffee St Fitz?',
      finalDescription: 'Menú, mapa, horario y contacto quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rápido',
      heading: 'Contacto y ubicación',
      whatsappTitle: 'WhatsApp / teléfono',
      reservationTitle: 'Pedido o consulta',
      reservationDescription: 'Genera un mensaje listo para continuar por WhatsApp.',
      emailTitle: 'Sitio / contacto',
    },
  },
  menuCategories: [
    { id: 'desayunos', name: 'Desayunos', description: 'Opciones completas para empezar el día' },
    { id: 'dulce', name: 'Dulce', description: 'Hotcakes, waffles y antojos' },
    { id: 'salado', name: 'Salado', description: 'Brunch, sándwiches y platos ligeros' },
    { id: 'cafe', name: 'Café', description: 'Espresso, latte y bebidas especiales' },
    { id: 'frias', name: 'Frías', description: 'Smoothies, jugos y bebidas frescas' },
  ],
  menuItems: [
    { id: 'm1', categoryId: 'desayunos', name: 'Desayuno americano', description: 'Hotcakes, huevo al gusto y acompañamientos.', price: '$185', tag: 'popular', featured: true },
    { id: 'm2', categoryId: 'desayunos', name: 'Huevos motuleños', description: 'Clásico yucateco para una mañana completa.', price: '$165', featured: true },
    { id: 'm3', categoryId: 'desayunos', name: 'Parfait de fruta', description: 'Yogurt, granola y fruta fresca.', price: '$120' },
    { id: 'm4', categoryId: 'dulce', name: 'Hotcakes especiales', description: 'Torre de hotcakes con fruta y toppings.', price: '$175', tag: 'signature', featured: true },
    { id: 'm5', categoryId: 'dulce', name: 'French toast', description: 'Pan dorado, fruta y miel.', price: '$170' },
    { id: 'm6', categoryId: 'salado', name: 'Chapata bomba', description: 'Sándwich fuerte de mañana con pan tostado.', price: '$165', featured: true },
    { id: 'm7', categoryId: 'salado', name: 'Toast de aguacate', description: 'Pan artesanal, aguacate y toque cítrico.', price: '$150', tag: 'popular' },
    { id: 'm8', categoryId: 'salado', name: 'Chilaquiles con tasajo', description: 'Crujientes, salseados y servidos para compartir.', price: '$160' },
    { id: 'm9', categoryId: 'cafe', name: 'Latte', description: 'Espresso con leche vaporizada.', price: '$78', tag: 'signature', featured: true },
    { id: 'm10', categoryId: 'cafe', name: 'Cold brew', description: 'Extracción en frío, suave y refrescante.', price: '$85' },
    { id: 'm11', categoryId: 'frias', name: 'Smoothie de frutos rojos', description: 'Bebida fresca para acompañar el desayuno.', price: '$95' },
    { id: 'm12', categoryId: 'frias', name: 'Jugo verde', description: 'Jugo natural con perfil fresco y ligero.', price: '$89' },
  ],
  promotions: [
    { id: 'p1', title: 'Desayuno americano', description: 'Un plato directo y fácil de elegir para la primera visita.', badge: 'Favorito', ctaLabel: 'Explorar menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Café para llevar', description: 'Un contacto rápido para resolver pedidos o dudas desde WhatsApp.', badge: 'Rápido', ctaLabel: 'Escríbenos', ctaAction: 'whatsapp' },
    { id: 'p3', title: 'Pan del día', description: 'Una razón simple para volver en la mañana.', badge: 'Mañana', ctaLabel: 'Cómo llegar', ctaAction: 'link', ctaValue: 'https://maps.google.com/maps/place//data=!4m2!3m1!1s0x8f5677e63382587b:0xe9cec5c746b63b94?entry=s' },
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=900&auto=format&fit=crop&q=80', alt: 'Desayuno servido en mesa', caption: 'Mañanas completas', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&auto=format&fit=crop&q=80', alt: 'Café servido en barra', caption: 'Café de todos los días', category: 'drinks' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=900&auto=format&fit=crop&q=80', alt: 'Interior de cafetería', caption: 'Espacio cálido', category: 'interior' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=900&auto=format&fit=crop&q=80', alt: 'Plato de brunch con huevo y pan', caption: 'Brunch casual', category: 'food' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=900&auto=format&fit=crop&q=80', alt: 'Bebida fría en vaso', caption: 'Bebidas frescas', category: 'drinks' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=900&auto=format&fit=crop&q=80', alt: 'Mesa de cafetería iluminada', caption: 'Pausa de mañana', category: 'interior' },
  ],
  testimonials: [
    { id: 't1', name: 'Cliente local', source: 'Google', rating: 5, text: 'Buen lugar para desayunar y resolver café rápido por la mañana.', date: '2026' },
    { id: 't2', name: 'Visitante', source: 'Direct', rating: 5, text: 'Carta variada, ambiente amable y opciones fáciles para volver.', date: '2026' },
    { id: 't3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Desayunos, comidas, jugos, cafés y pan recién horneado en un solo lugar.', date: '2026' },
  ],
  faqs: [
    { question: 'Qué ofrece Coffee St Fitz?', answer: 'Desayunos, café, pan del día, jugos, smoothies y opciones dulces y saladas.' },
    { question: 'Cómo puedo contactarlos?', answer: 'El flujo principal del sitio abre WhatsApp con un mensaje listo para enviar.' },
  ],
  reservation: {
    enabled: true,
    mode: 'mock',
    maxGuests: 8,
    minAdvanceHours: 1,
    timeSlots: ['07:30', '08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00', '13:30'],
    guestOptions: [1, 2, 3, 4, 5, 6, 7, 8],
    modalTitle: 'Contacto rápido Coffee St Fitz',
    modalDescription: 'Completa el formulario y genera un mensaje listo para continuar por WhatsApp.',
    successTitle: 'Solicitud lista',
    successDescription: 'Tu mensaje quedó preparado para continuar por WhatsApp.',
    previewLabel: 'Vista previa del mensaje',
    openWhatsappLabel: 'Abrir conversación',
    messageTemplate: 'Hola Coffee St Fitz. Quisiera información sobre menú, pedido o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529991582029',
  },
  whatsapp: {
    number: '529991582029',
    defaultMessage: 'Hola Coffee St Fitz, quisiera información sobre menú, sucursal u horario.',
    floatingButton: true,
    ariaLabel: 'Contactar por WhatsApp',
  },
  location: {
    address: 'Sucursal Mérida',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97120',
    country: 'México',
    googleMapsUrl: 'https://maps.google.com/maps/place//data=!4m2!3m1!1s0x8f5677e63382587b:0xe9cec5c746b63b94?entry=s',
    mapAriaLabel: 'Mapa de ubicación Coffee St Fitz en Mérida',
    mapImageAlt: 'Mapa referencial de Coffee St Fitz en Mérida',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '7:30 am - 2:30 pm' },
      { day: 'Martes', hours: '7:30 am - 2:30 pm' },
      { day: 'Miércoles', hours: '7:30 am - 2:30 pm' },
      { day: 'Jueves', hours: '7:30 am - 2:30 pm' },
      { day: 'Viernes', hours: '7:30 am - 2:30 pm' },
      { day: 'Sábado', hours: '7:30 am - 2:30 pm' },
      { day: 'Domingo', hours: '8:00 am - 2:00 pm' },
    ],
    phone: '+52 999 158 2029',
    email: 'contacto@coffeestfitz.com',
  },
  social: {
    instagram: 'https://www.instagram.com/coffee_st_fitz/',
    facebook: 'https://www.facebook.com/coffeestfitz/',
  },
};
