import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const DLU_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'dlu-merida',
  name: "D'LU",
  tagline: 'Comida mexicana casera cerca de Paseo Montejo',
  category: 'restaurant',
  concept: 'Restaurante mexicano de comida económica y trato amable, ubicado cerca del Museo de la Ciudad y la zona de Paseo Montejo.',
  identity: {
    id: 'dlu-merida',
    name: "D'LU",
    tagline: 'Comida mexicana casera cerca de Paseo Montejo',
    category: 'restaurant',
    concept: 'Restaurante mexicano de comida económica y trato amable, ubicado cerca del Museo de la Ciudad y la zona de Paseo Montejo.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.5 0.12 40)',
    accentColor: 'oklch(0.68 0.13 80)',
    bgBase: 'oklch(0.98 0.012 76)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.5 0.12 40)',
    primaryHover: 'oklch(0.42 0.12 40)',
    accent: 'oklch(0.68 0.13 80)',
    cta: 'oklch(0.46 0.14 32)',
    background: 'oklch(0.98 0.012 76)',
    surface: 'oklch(0.995 0.006 76)',
    surfaceAlt: 'oklch(0.94 0.025 74)',
    border: 'oklch(0.84 0.026 72)',
    text: 'oklch(0.23 0.034 56)',
    textMuted: 'oklch(0.43 0.032 56)',
  },
  seo: {
    title: "D'LU Mérida - Comida mexicana casera",
    description: "D'LU en Mérida: comida mexicana, sopa, tinga de pollo, sopes, empanadas y almuerzo cerca de Paseo Montejo.",
    keywords: ["d'lu mérida", 'comida mexicana mérida', 'almuerzo mérida', 'paseo montejo comida', 'sopes mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: "D'LU\ncomida mexicana sin complicaciones",
    subheadline: 'Sopa, tinga de pollo, sopes y antojitos en una experiencia clara para almorzar cerca de Paseo Montejo.',
    ctaLabel: 'Ver menú',
    ctaSecondaryLabel: 'Cómo llegar',
    locationLabel: 'Calle 43 esquina con 54',
    backgroundImage: 'https://images.unsplash.com/photo-1625167171750-419e95f877d8?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1625167171750-419e95f877d8?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Comida mexicana casera servida en mesa',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Comida mexicana',
      heading: 'Una carta casera que necesita presencia propia',
      lead: 'La información pública destaca sopa, tinga de pollo, sopes, empanadas y servicio amable con precio accesible.',
      body: 'El sitio enfoca la propuesta en almuerzos rápidos, ubicación clara y contacto simple para convertir búsquedas locales en visitas.',
      foundedLabel: 'Zona Paseo Montejo',
    },
    menuHighlights: {
      eyebrow: 'Menú destacado',
      heading: 'Sopa, tinga, sopes y antojitos',
      subheading: 'Una selección corta basada en los platillos mencionados públicamente y en categorías mexicanas fáciles de vender.',
      fullMenuLabel: 'Explorar menú',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Buen valor, servicio amable y ambiente tranquilo',
      subheading: 'La reputación pública lo posiciona como opción económica y confiable para lunch/brunch.',
      proofItems: [
        { value: '4.7', label: 'Rating Google' },
        { value: '86', label: 'Reseñas visibles' },
        { value: '$', label: 'Precio accesible' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: "Encuentra D'LU cerca de Paseo Montejo",
    },
    menuPage: {
      eyebrow: 'Mexicano casual',
      heading: "Menú D'LU",
      lead: 'Comida mexicana casera, almuerzos, sopes, empanadas y guisos del día.',
      finalHeading: "¿Listo para visitar D'LU?",
      finalDescription: 'La ubicación, el horario y el contacto quedan claros desde móvil.',
    },
  },
  menuCategories: [
    { id: 'antojitos', name: 'Antojitos', description: 'Sopes, empanadas y tacos' },
    { id: 'guisos', name: 'Guisos', description: 'Tinga, mole y opciones caseras' },
    { id: 'caldos', name: 'Caldos', description: 'Sopas y platos de cuchara' },
    { id: 'bebidas', name: 'Bebidas', description: 'Aguas frescas y bebidas de comida' },
  ],
  menuItems: [
    { id: 'dlu1', categoryId: 'antojitos', name: 'Sopes de la casa', description: 'Sopes mexicanos con guiso y salsa.', price: '$85', tag: 'popular', featured: true },
    { id: 'dlu2', categoryId: 'guisos', name: 'Tinga de pollo', description: 'Guiso de pollo deshebrado con sabor casero.', price: '$95', tag: 'signature', featured: true },
    { id: 'dlu3', categoryId: 'caldos', name: 'Sopa del día', description: 'Sopa casera para almuerzo ligero.', price: '$65', featured: true },
    { id: 'dlu4', categoryId: 'antojitos', name: 'Empanadas', description: 'Empanadas doradas con relleno de la casa.', price: '$80' },
    { id: 'dlu5', categoryId: 'guisos', name: 'Mole con pollo', description: 'Plato mexicano para comida corrida.', price: '$110' },
    { id: 'dlu6', categoryId: 'antojitos', name: 'Tacos de guiso', description: 'Tacos servidos con salsa y guarnición.', price: '$75' },
    { id: 'dlu7', categoryId: 'bebidas', name: 'Agua fresca', description: 'Bebida fresca del día.', price: '$35' },
    { id: 'dlu8', categoryId: 'bebidas', name: 'Refresco', description: 'Bebida embotellada.', price: '$35' },
  ],
  promotions: [
    { id: 'dlup1', title: 'Lunch casero', description: 'Una oferta clara para quien busca comer bien cerca de Paseo Montejo.', badge: 'Lunch', ctaLabel: 'Ver menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'dlup2', title: 'Antojitos rápidos', description: 'Sopes, empanadas y tacos como gancho visual y de conversión.', badge: 'Casero', ctaLabel: 'Escribir', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'dlut1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputación pública destaca comida rica, económica y trato amable.', date: '2026' },
    { id: 'dlut2', name: 'Visitante', source: 'Google', rating: 5, text: 'Una opción mexicana casual para almuerzo o brunch cerca del centro.', date: '2026' },
    { id: 'dlut3', name: 'Perfil público', source: 'Direct', rating: 5, text: 'Sopes, tinga, sopa y empanadas son señales de una carta fácil de explicar.', date: '2026' },
  ],
  faqs: [
    { question: "¿Qué tipo de comida ofrece D'LU?", answer: 'Comida mexicana casera, antojitos, guisos, sopa, tinga de pollo y sopes.' },
    { question: "¿Cuál es el horario publicado?", answer: 'De lunes a viernes de 9:00 am a 6:00 pm; sábado y domingo cerrado según el listado público consultado.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: "Contacto rápido D'LU",
    messageTemplate: "Hola D'LU. Quisiera información sobre menú o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}",
    whatsappNumber: '529991692360',
  },
  whatsapp: {
    number: '529991692360',
    defaultMessage: "Hola D'LU, quisiera información sobre menú, horario o ubicación.",
    floatingButton: true,
    ariaLabel: "Contactar a D'LU por WhatsApp",
  },
  location: {
    address: 'Calle 43 esquina con 54, Zona Paseo Montejo',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97000',
    country: 'México',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=D%27LU%20Calle%2043%20esquina%20con%2054%20Merida',
    mapAriaLabel: "Mapa de ubicación de D'LU en Mérida",
    mapImageAlt: "Mapa referencial de D'LU en Mérida",
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '9:00 am - 6:00 pm' },
      { day: 'Martes', hours: '9:00 am - 6:00 pm' },
      { day: 'Miércoles', hours: '9:00 am - 6:00 pm' },
      { day: 'Jueves', hours: '9:00 am - 6:00 pm' },
      { day: 'Viernes', hours: '9:00 am - 6:00 pm' },
      { day: 'Sábado', hours: 'Cerrado', closed: true },
      { day: 'Domingo', hours: 'Cerrado', closed: true },
    ],
    phone: '+52 999 169 2360',
    email: 'contacto@dlu.mx',
  },
  social: {},
};
