import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const EH_VOILA_VALLADOLID_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'eh-voila-valladolid',
  name: 'Eh Voila! Valladolid',
  tagline: 'Cocina internacional hecha en casa',
  category: 'restaurant',
  concept: 'Restaurante familiar casual chic de cocina internacional casera, con opciones gluten free, veganas y dairy free para una comunidad amplia.',
  identity: {
    id: 'eh-voila-valladolid',
    name: 'Eh Voila! Valladolid',
    tagline: 'Cocina internacional hecha en casa',
    category: 'restaurant',
    concept: 'Restaurante familiar casual chic de cocina internacional casera, con opciones gluten free, veganas y dairy free para una comunidad amplia.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.38 0.08 34)',
    accentColor: 'oklch(0.56 0.08 150)',
    bgBase: 'oklch(0.984 0.012 84)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.38 0.08 34)',
    primaryHover: 'oklch(0.38 0.08 34)',
    accent: 'oklch(0.56 0.08 150)',
    cta: 'oklch(0.72 0.12 78)',
    background: 'oklch(0.984 0.012 84)',
    surface: 'oklch(0.998 0.005 84)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.22 0.035 45)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Eh Voila! Valladolid - Cocina internacional hecha en casa',
    description: 'Eh Voila! Valladolid: Restaurante familiar casual chic de cocina internacional casera, con opciones gluten free, veganas y dairy free para una comunidad amplia.',
    keywords: ['Eh Voila! Valladolid', 'Cocina internacional hecha en casa', 'Valladolid, Yucatan', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Eh Voila!\ninternacional y hecho en casa',
    subheadline: 'Un sitio amable para hacer visible variedad, opciones especiales, ubicacion y contacto a familias, viajeros y comunidad local.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Valladolid, Yucatan',
    backgroundImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Eh Voila! Valladolid - Valladolid, Yucatan',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Eh Voila! Valladolid ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Eh Voila! Valladolid',
      lead: 'Eh Voila! gana por amplitud: comida internacional casera, opcion para familias y sensibilidad real a restricciones alimentarias.',
      body: 'La web debe hacer esa accesibilidad evidente desde el inicio: categorias claras, sellos gluten free/vegano/dairy free y un contacto facil.',
      foundedLabel: 'Valladolid, Yucatan',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Cocina internacional hecha en casa',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '4.7k', label: 'Seguidores IG' },
        { value: 'GF', label: 'Opciones especiales' },
        { value: 'Familia', label: 'Ambiente casual' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Eh Voila! Valladolid en Valladolid, Yucatan',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Eh Voila! Valladolid',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Eh Voila! Valladolid?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'internacional', name: 'Internacional', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'gluten-free', name: 'Gluten free', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'vegano', name: 'Vegano', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'familia', name: 'Familia', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'postres', name: 'Postres', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'internacional', name: 'Pasta artesanal', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'gluten-free', name: 'Ensalada de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'vegano', name: 'Plato vegano del dia', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'familia', name: 'Crepa salada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'postres', name: 'Hamburguesa casual', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'internacional', name: 'Opcion gluten free', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'gluten-free', name: 'Postre casero', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm8', categoryId: 'vegano', name: 'Bebida fresca', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' }
  ],
  promotions: [
    { id: 'p1', title: 'Opciones para todos', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Hecho en casa', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1800&auto=format&fit=crop&q=85', alt: 'Eh Voila! Valladolid preview image 1', caption: 'Eh Voila! Valladolid', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1000&auto=format&fit=crop&q=85', alt: 'Eh Voila! Valladolid preview image 2', caption: 'Eh Voila! Valladolid', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=1600&auto=format&fit=crop&q=85', alt: 'Eh Voila! Valladolid preview image 3', caption: 'Eh Voila! Valladolid', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&auto=format&fit=crop&q=80', alt: 'Eh Voila! Valladolid preview image 4', caption: 'Eh Voila! Valladolid', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1800&auto=format&fit=crop&q=85', alt: 'Eh Voila! Valladolid preview image 5', caption: 'Eh Voila! Valladolid', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1000&auto=format&fit=crop&q=85', alt: 'Eh Voila! Valladolid preview image 6', caption: 'Eh Voila! Valladolid', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 4.7k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Eh Voila! Valladolid?', answer: 'Restaurante familiar casual chic de cocina internacional casera, con opciones gluten free, veganas y dairy free para una comunidad amplia.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Eh Voila! Valladolid',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Eh Voila! Valladolid. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529850000000',
  },
  whatsapp: {
    number: '529850000000',
    defaultMessage: 'Hola Eh Voila! Valladolid, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Eh Voila! Valladolid por WhatsApp',
  },
  location: {
    address: 'Valladolid, Yucatan',
    city: 'Valladolid',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Eh%20Voila!%20Valladolid%20Valladolid%2C%20Yucatan',
    mapAriaLabel: 'Mapa de ubicacion de Eh Voila! Valladolid',
    mapImageAlt: 'Mapa referencial de Eh Voila! Valladolid',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 985 000 0000',
    email: 'hola@ehvoilavalladolid.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/ehvoila_valladolid/',
  },
};

