import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const EL_MESON_MERIDA_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'el-meson-merida',
  name: 'El Meson',
  tagline: 'Comida espanola en el Centro de Merida',
  category: 'restaurant',
  concept: 'Restaurante pequeno y especializado en cocina espanola, con paella 2x1 martes y jueves y una base leal que puede crecer digitalmente.',
  identity: {
    id: 'el-meson-merida',
    name: 'El Meson',
    tagline: 'Comida espanola en el Centro de Merida',
    category: 'restaurant',
    concept: 'Restaurante pequeno y especializado en cocina espanola, con paella 2x1 martes y jueves y una base leal que puede crecer digitalmente.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.36 0.12 28)',
    accentColor: 'oklch(0.47 0.1 250)',
    bgBase: 'oklch(0.982 0.014 82)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.36 0.12 28)',
    primaryHover: 'oklch(0.36 0.12 28)',
    accent: 'oklch(0.47 0.1 250)',
    cta: 'oklch(0.74 0.15 78)',
    background: 'oklch(0.982 0.014 82)',
    surface: 'oklch(0.998 0.006 82)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.2 0.035 36)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'El Meson - Comida espanola en el Centro de Merida',
    description: 'El Meson: Restaurante pequeno y especializado en cocina espanola, con paella 2x1 martes y jueves y una base leal que puede crecer digitalmente.',
    keywords: ['El Meson', 'Comida espanola en el Centro de Merida', 'Centro, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'El Meson\npaella y cocina espanola',
    subheadline: 'Una web sencilla y apetecible para que la especialidad se entienda rapido: paella, tapas, promociones, mapa y reserva por WhatsApp.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Centro, Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'El Meson - Centro, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'El Meson ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor El Meson',
      lead: 'El Meson no necesita competir como restaurante generico: su oportunidad esta en ser la respuesta clara a comida espanola en Merida.',
      body: 'El sitio debe empujar la especialidad: paella, promociones semanales, platos espanoles reconocibles y contacto directo para reservar.',
      foundedLabel: 'Centro, Merida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Comida espanola en el Centro de Merida',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '2x1', label: 'Paella semanal' },
        { value: '1.1k', label: 'Comunidad leal' },
        { value: 'Centro', label: 'Especialidad clara' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra El Meson en Centro, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu El Meson',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar El Meson?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'paellas', name: 'Paellas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'tapas', name: 'Tapas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'espanoles', name: 'Espanoles', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'vinos', name: 'Vinos', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'postres', name: 'Postres', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'paellas', name: 'Paella de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'tapas', name: 'Paella mixta', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'espanoles', name: 'Tortilla espanola', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'vinos', name: 'Croquetas', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'postres', name: 'Pulpo a la gallega', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'paellas', name: 'Pan con tomate', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'tapas', name: 'Sangria', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm8', categoryId: 'espanoles', name: 'Crema catalana', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' }
  ],
  promotions: [
    { id: 'p1', title: 'Paella 2x1 martes y jueves', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Reserva para compartir', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1800&auto=format&fit=crop&q=85', alt: 'El Meson preview image 1', caption: 'El Meson', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=1000&auto=format&fit=crop&q=85', alt: 'El Meson preview image 2', caption: 'El Meson', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1600&auto=format&fit=crop&q=85', alt: 'El Meson preview image 3', caption: 'El Meson', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=600&auto=format&fit=crop&q=80', alt: 'El Meson preview image 4', caption: 'El Meson', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=1800&auto=format&fit=crop&q=85', alt: 'El Meson preview image 5', caption: 'El Meson', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1604909052743-94e838986d24?w=1000&auto=format&fit=crop&q=85', alt: 'El Meson preview image 6', caption: 'El Meson', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 1.1k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a El Meson?', answer: 'Restaurante pequeno y especializado en cocina espanola, con paella 2x1 martes y jueves y una base leal que puede crecer digitalmente.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido El Meson',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola El Meson. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola El Meson, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a El Meson por WhatsApp',
  },
  location: {
    address: 'Centro, Merida',
    city: 'Centro',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=El%20Meson%20Centro%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de El Meson',
    mapImageAlt: 'Mapa referencial de El Meson',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'reservas@elmesonmerida.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/elmeson_mid/',
  },
};

