import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const RINCON_DEL_PACIFICO_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'el-rincon-del-pacifico',
  name: 'El Rincon del Pacifico',
  tagline: 'Mariscos estilo Sinaloa en Merida',
  category: 'restaurant',
  concept: 'Mariscos casuales estilo Sinaloa, nuevos en Merida, con platos virales como tostada mitotera y tacos de camaron.',
  identity: {
    id: 'el-rincon-del-pacifico',
    name: 'El Rincon del Pacifico',
    tagline: 'Mariscos estilo Sinaloa en Merida',
    category: 'restaurant',
    concept: 'Mariscos casuales estilo Sinaloa, nuevos en Merida, con platos virales como tostada mitotera y tacos de camaron.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.42 0.12 218)',
    accentColor: 'oklch(0.62 0.13 190)',
    bgBase: 'oklch(0.98 0.018 205)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.42 0.12 218)',
    primaryHover: 'oklch(0.42 0.12 218)',
    accent: 'oklch(0.62 0.13 190)',
    cta: 'oklch(0.74 0.16 62)',
    background: 'oklch(0.98 0.018 205)',
    surface: 'oklch(0.996 0.006 205)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.18 0.04 225)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'El Rincon del Pacifico - Mariscos estilo Sinaloa en Merida',
    description: 'El Rincon del Pacifico: Mariscos casuales estilo Sinaloa, nuevos en Merida, con platos virales como tostada mitotera y tacos de camaron.',
    keywords: ['El Rincon del Pacifico', 'Mariscos estilo Sinaloa en Merida', 'Colonia Maya, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'El Rincon del Pacifico\nSinaloa servido fresco',
    subheadline: 'Un sitio directo para antojo de mariscos: fotos claras, favoritos, ubicacion y WhatsApp para llegar o preguntar rapido.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Colonia Maya, Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'El Rincon del Pacifico - Colonia Maya, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'El Rincon del Pacifico ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor El Rincon del Pacifico',
      lead: 'La marca compite por antojo inmediato: mariscos frescos, porciones provocadoras y contenido con alta respuesta.',
      body: 'La web debe reducir friccion: mostrar los platos que jalan visitas, destacar prueba social y abrir mapa o WhatsApp sin hacer buscar entre reels.',
      foundedLabel: 'Colonia Maya, Merida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Mariscos estilo Sinaloa en Merida',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '5.0', label: 'TripAdvisor publico' },
        { value: '2024', label: 'Marca nueva' },
        { value: '7.2k', label: 'Seguidores IG' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra El Rincon del Pacifico en Colonia Maya, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu El Rincon del Pacifico',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar El Rincon del Pacifico?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'tostadas', name: 'Tostadas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'tacos', name: 'Tacos', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'aguachiles', name: 'Aguachiles', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'caldos', name: 'Caldos', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'bebidas', name: 'Bebidas', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'tostadas', name: 'Tostada mitotera', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'tacos', name: 'Taco de camaron capeado', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'aguachiles', name: 'Aguachile verde', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'caldos', name: 'Tostada de atun', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'bebidas', name: 'Gobernador de camaron', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'tostadas', name: 'Ceviche del Pacifico', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'tacos', name: 'Caldo levanta animo', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm8', categoryId: 'aguachiles', name: 'Michelada preparada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' }
  ],
  promotions: [
    { id: 'p1', title: 'Tostada mitotera', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Tacos de camaron', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=1800&auto=format&fit=crop&q=85', alt: 'El Rincon del Pacifico preview image 1', caption: 'El Rincon del Pacifico', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=1000&auto=format&fit=crop&q=85', alt: 'El Rincon del Pacifico preview image 2', caption: 'El Rincon del Pacifico', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=1600&auto=format&fit=crop&q=85', alt: 'El Rincon del Pacifico preview image 3', caption: 'El Rincon del Pacifico', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=600&auto=format&fit=crop&q=80', alt: 'El Rincon del Pacifico preview image 4', caption: 'El Rincon del Pacifico', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=1800&auto=format&fit=crop&q=85', alt: 'El Rincon del Pacifico preview image 5', caption: 'El Rincon del Pacifico', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=1000&auto=format&fit=crop&q=85', alt: 'El Rincon del Pacifico preview image 6', caption: 'El Rincon del Pacifico', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 7.2k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a El Rincon del Pacifico?', answer: 'Mariscos casuales estilo Sinaloa, nuevos en Merida, con platos virales como tostada mitotera y tacos de camaron.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido El Rincon del Pacifico',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola El Rincon del Pacifico. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola El Rincon del Pacifico, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a El Rincon del Pacifico por WhatsApp',
  },
  location: {
    address: 'Colonia Maya, Merida',
    city: 'Colonia Maya',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=El%20Rincon%20del%20Pacifico%20Colonia%20Maya%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de El Rincon del Pacifico',
    mapImageAlt: 'Mapa referencial de El Rincon del Pacifico',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'contacto@rincondelpacifico.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/elrincondelpacifico.mid/',
  },
};

