import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const EL_TIO_RICARDO_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'el-tio-ricardo-merida',
  name: 'El Tío Ricardo',
  tagline: 'Parrilla norteña tradicional en Mérida',
  category: 'restaurant',
  concept: 'Restaurante mexicano y steakhouse de tradición familiar en García Ginerés, con cortes, queso fundido, guacamole, salchicha asada y ambiente de parrilla.',
  identity: {
    id: 'el-tio-ricardo-merida',
    name: 'El Tío Ricardo',
    tagline: 'Parrilla norteña tradicional en Mérida',
    category: 'restaurant',
    concept: 'Restaurante mexicano y steakhouse de tradición familiar en García Ginerés, con cortes, queso fundido, guacamole, salchicha asada y ambiente de parrilla.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.43 0.12 32)',
    accentColor: 'oklch(0.69 0.13 70)',
    bgBase: 'oklch(0.16 0.018 45)',
    darkMode: true,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'dark',
    primary: 'oklch(0.64 0.13 36)',
    primaryHover: 'oklch(0.72 0.13 36)',
    accent: 'oklch(0.74 0.12 72)',
    cta: 'oklch(0.59 0.16 30)',
    background: 'oklch(0.16 0.018 45)',
    surface: 'oklch(0.21 0.024 45)',
    surfaceAlt: 'oklch(0.27 0.03 45)',
    border: 'oklch(0.38 0.04 46)',
    text: 'oklch(0.96 0.008 75)',
    textMuted: 'oklch(0.77 0.025 75)',
    textInverse: 'oklch(0.14 0.02 45)',
    radius: 'classic',
    shadow: 'high',
  },
  seo: {
    title: 'El Tío Ricardo Mérida - Parrilla y cortes',
    description: 'El Tío Ricardo en Mérida: parrilla estilo Monterrey, cortes, queso fundido, guacamole, salchicha asada y comida mexicana.',
    keywords: ['el tío ricardo mérida', 'parrilla mérida', 'steakhouse mérida', 'cortes mérida', 'garcía ginerés restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'El Tío Ricardo\nparrilla clásica en Mérida',
    subheadline: 'Cortes, queso fundido, guacamole y tradición familiar en García Ginerés desde una presencia digital más clara.',
    ctaLabel: 'Ver menú',
    ctaSecondaryLabel: 'Cómo llegar',
    locationLabel: 'García Ginerés, Mérida',
    backgroundImage: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.62,
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Corte de carne servido en parrilla clásica',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Desde 1978',
      heading: 'Un clásico de parrilla que merece una página con peso propio',
      lead: 'Las referencias públicas lo describen como una parrilla estilo Monterrey con cortes, queso fundido, guacamole, salchichas y tortillas de harina.',
      body: 'La propuesta visual usa tonos de brasa, tipografía editorial y CTAs simples para reservas, ubicación y contacto, cuidando una sensación tradicional sin verse anticuada.',
      foundedLabel: 'García Ginerés',
    },
    menuHighlights: {
      eyebrow: 'Especialidades',
      heading: 'Cortes, entradas norteñas y sobremesa',
      subheading: 'Una carta robusta para comidas familiares, cenas y visitas de fin de semana.',
      fullMenuLabel: 'Explorar menú',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Tradición familiar y parrilla reconocida',
      subheading: 'Los listados públicos destacan alto volumen de reseñas, ambiente familiar, cortes y servicio.',
      proofItems: [
        { value: '4.5', label: 'Rating Google' },
        { value: '1.6k', label: 'Reseñas visibles' },
        { value: '1978', label: 'Historia pública' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Encuentra El Tío Ricardo en García Ginerés',
    },
    menuPage: {
      eyebrow: 'Parrilla norteña',
      heading: 'Menú El Tío Ricardo',
      lead: 'Cortes, queso fundido, guacamole, salchicha asada, flan y bebidas para comida o cena.',
      finalHeading: '¿Listo para visitar El Tío Ricardo?',
      finalDescription: 'Reserva, ubicación, horario y contacto quedan visibles desde cualquier pantalla.',
    },
  },
  menuCategories: [
    { id: 'entradas', name: 'Entradas', description: 'Para abrir mesa y compartir' },
    { id: 'cortes', name: 'Cortes', description: 'Parrilla y steakhouse' },
    { id: 'especiales', name: 'Especiales', description: 'Platos de la casa' },
    { id: 'postres', name: 'Postres', description: 'Cierre clásico' },
    { id: 'bebidas', name: 'Bebidas', description: 'Bar, cerveza y bebidas frescas' },
  ],
  menuItems: [
    { id: 'etr1', categoryId: 'entradas', name: 'Queso fundido', description: 'Entrada norteña para compartir al centro.', price: '$150', tag: 'popular', featured: true },
    { id: 'etr2', categoryId: 'entradas', name: 'Guacamole con totopos', description: 'Guacamole fresco para abrir la mesa.', price: '$130', featured: true },
    { id: 'etr3', categoryId: 'entradas', name: 'Salchicha asada', description: 'Entrada de parrilla mencionada públicamente.', price: '$145' },
    { id: 'etr4', categoryId: 'cortes', name: 'Arrachera marinada', description: 'Corte recomendado en reseñas públicas.', price: '$390', tag: 'signature', featured: true },
    { id: 'etr5', categoryId: 'cortes', name: 'Rib eye', description: 'Corte de parrilla para comida o cena.', price: '$520', featured: true },
    { id: 'etr6', categoryId: 'cortes', name: 'Filete mignon', description: 'Corte clásico destacado en listados públicos.', price: '$480' },
    { id: 'etr7', categoryId: 'especiales', name: 'Sándwich de rib eye', description: 'Opción inspirada en menciones públicas de steak sandwich.', price: '$290' },
    { id: 'etr8', categoryId: 'postres', name: 'Flan napolitano', description: 'Postre clásico recomendado públicamente.', price: '$95' },
    { id: 'etr9', categoryId: 'bebidas', name: 'Limonada', description: 'Bebida fresca para acompañar parrilla.', price: '$65' },
  ],
  promotions: [
    { id: 'etrp1', title: 'Mesa de parrilla', description: 'Cortes, entradas y bebidas para una comida familiar fácil de reservar.', badge: 'Parrilla', ctaLabel: 'Ver menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'etrp2', title: 'Reserva de fin de semana', description: 'Un CTA directo para fechas con más demanda y grupos grandes.', badge: 'Reserva', ctaLabel: 'Contactar', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'etrt1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputación pública destaca cortes, entradas norteñas y ambiente familiar.', date: '2026' },
    { id: 'etrt2', name: 'Visitante', source: 'TripAdvisor', rating: 4, text: 'Un restaurante tradicional de Mérida para comida mexicana y steakhouse.', date: '2026' },
    { id: 'etrt3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Una historia de parrilla que puede comunicar mejor reservas, ubicación y menú.', date: '2026' },
  ],
  faqs: [
    { question: '¿Qué tipo de comida ofrece El Tío Ricardo?', answer: 'Parrilla estilo Monterrey, cortes, queso fundido, guacamole, salchicha asada, comida mexicana y postres clásicos.' },
    { question: '¿Dónde está ubicado?', answer: 'En C. 8 201-X 23, García Ginerés, Mérida, Yucatán.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    maxGuests: 12,
    timeSlots: ['12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00'],
    modalTitle: 'Reserva en El Tío Ricardo',
    messageTemplate: 'Hola El Tío Ricardo. Quisiera información para reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529999252967',
  },
  whatsapp: {
    number: '529999252967',
    defaultMessage: 'Hola El Tío Ricardo, quisiera información sobre menú, reservas u horario.',
    floatingButton: true,
    ariaLabel: 'Contactar a El Tío Ricardo por WhatsApp',
  },
  location: {
    address: 'C. 8 201-X 23, García Ginerés',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97070',
    country: 'México',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=El%20Tio%20Ricardo%20C.%208%20201-X%2023%20Garcia%20Gineres%20Merida',
    mapAriaLabel: 'Mapa de ubicación de El Tío Ricardo en Mérida',
    mapImageAlt: 'Mapa referencial de El Tío Ricardo en Mérida',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '12:00 pm - 10:00 pm' },
      { day: 'Martes', hours: '12:00 pm - 10:00 pm' },
      { day: 'Miércoles', hours: '12:00 pm - 10:00 pm' },
      { day: 'Jueves', hours: '12:00 pm - 10:00 pm' },
      { day: 'Viernes', hours: '12:00 pm - 10:00 pm' },
      { day: 'Sábado', hours: '12:00 pm - 10:00 pm' },
      { day: 'Domingo', hours: '12:00 pm - 10:00 pm' },
    ],
    phone: '+52 999 925 2967',
    email: 'contacto@eltioricardo.com.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/eltioricardomid/',
    facebook: 'https://www.facebook.com/',
  },
};
