import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const HOLA_SANTIAGO_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'hola-santiago-merida',
  name: 'Hola Santiago',
  tagline: 'Café, panadería y bocados de mañana',
  category: 'cafe',
  concept: 'Café de barrio en Santiago con bebidas de café, panadería, jugos y bocados rápidos para visitantes y vecinos del centro de Mérida.',
  identity: {
    id: 'hola-santiago-merida',
    name: 'Hola Santiago',
    tagline: 'Café, panadería y bocados de mañana',
    category: 'cafe',
    concept: 'Café de barrio en Santiago con bebidas de café, panadería, jugos y bocados rápidos para visitantes y vecinos del centro de Mérida.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.48 0.095 128)',
    accentColor: 'oklch(0.69 0.11 72)',
    bgBase: 'oklch(0.985 0.014 82)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.48 0.095 128)',
    primaryHover: 'oklch(0.4 0.095 128)',
    accent: 'oklch(0.69 0.11 72)',
    cta: 'oklch(0.54 0.12 42)',
    background: 'oklch(0.985 0.014 82)',
    surface: 'oklch(0.997 0.006 82)',
    surfaceAlt: 'oklch(0.94 0.026 96)',
    border: 'oklch(0.84 0.028 92)',
    text: 'oklch(0.24 0.032 82)',
    textMuted: 'oklch(0.43 0.03 88)',
  },
  seo: {
    title: 'Hola Santiago Mérida - Café en Barrio de Santiago',
    description: 'Hola Santiago en Mérida: café, panadería, jugos y bocados rápidos cerca del Barrio de Santiago.',
    keywords: ['hola santiago', 'café santiago mérida', 'cafetería mérida centro', 'bagels mérida', 'panadería mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Hola Santiago\ncafé de barrio en Mérida',
    subheadline: 'Café, pan recién hecho, jugos y bocados rápidos en un espacio cálido del Barrio de Santiago.',
    ctaLabel: 'Ver menú',
    ctaSecondaryLabel: 'Cómo llegar',
    locationLabel: 'Barrio de Santiago, Centro',
    backgroundImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.28,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escribir',
    stickyLabel: 'Ver menú',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Cafetería cálida con pan y café sobre una mesa',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Barrio de Santiago',
      heading: 'Un café pequeño con señales claras para decidir rápido',
      lead: 'La presencia pública apunta a café, panadería, jugos, pastries y bocados como bagels en un espacio acogedor de Santiago.',
      body: 'El sitio convierte esa energía local en una página móvil directa: menú breve, horarios, ubicación, teléfono e Instagram siempre visibles.',
      foundedLabel: 'Centro de Mérida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos',
      heading: 'Café, pan y bocados para empezar el día',
      subheading: 'Una carta corta y fácil de escanear para turistas, vecinos y visitas rápidas antes de caminar el centro.',
      fullMenuLabel: 'Explorar menú',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Un café con reputación de joya local',
      subheading: 'La información pública destaca café, pastries, jugos, servicio amable y ambiente acogedor.',
      proofItems: [
        { value: '4.7', label: 'Rating público' },
        { value: '50', label: 'Reseñas visibles' },
        { value: '7:30', label: 'Apertura entre semana' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Encuentra Hola Santiago en el Barrio de Santiago',
    },
    menuPage: {
      eyebrow: 'Café + panadería',
      heading: 'Menú Hola Santiago',
      lead: 'Bebidas de café, jugos, pastries y bocados rápidos para una mañana tranquila en el centro.',
      finalHeading: '¿Listo para visitar Hola Santiago?',
      finalDescription: 'El sitio deja menú, mapa, horario y contacto a un toque.',
    },
  },
  menuCategories: [
    { id: 'cafe', name: 'Café', description: 'Bebidas calientes y frías' },
    { id: 'panaderia', name: 'Panadería', description: 'Pastries y panes del día' },
    { id: 'bocados', name: 'Bocados', description: 'Bagels y opciones rápidas' },
    { id: 'jugos', name: 'Jugos', description: 'Bebidas frescas para la mañana' },
  ],
  menuItems: [
    { id: 'hs1', categoryId: 'cafe', name: 'Latte de la casa', description: 'Espresso con leche cremosa para tomar en barra o mesa.', price: '$75', tag: 'popular', featured: true },
    { id: 'hs2', categoryId: 'cafe', name: 'Cold coffee', description: 'Café frío para caminar el centro de Mérida.', price: '$82' },
    { id: 'hs3', categoryId: 'panaderia', name: 'Croissant de almendra', description: 'Pieza de panadería mencionada en reseñas públicas.', price: '$95', tag: 'signature', featured: true },
    { id: 'hs4', categoryId: 'panaderia', name: 'Pan del día', description: 'Selección de pan horneado para acompañar café.', price: '$70' },
    { id: 'hs5', categoryId: 'bocados', name: 'Bagel bacon, egg & cheese', description: 'Bagel salado inspirado en los bocados destacados públicamente.', price: '$145', featured: true },
    { id: 'hs6', categoryId: 'bocados', name: 'Bagel de la mañana', description: 'Bagel tostado con spread de la casa.', price: '$125' },
    { id: 'hs7', categoryId: 'jugos', name: 'Jugo fresco', description: 'Opción ligera para acompañar panadería y café.', price: '$70' },
    { id: 'hs8', categoryId: 'jugos', name: 'Limonada fría', description: 'Bebida fresca para el calor del centro.', price: '$65' },
  ],
  promotions: [
    { id: 'hsp1', title: 'Café + pastry', description: 'Un combo claro para atraer visitas de mañana.', badge: 'Mañana', ctaLabel: 'Ver menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'hsp2', title: 'Bagel rápido', description: 'Ideal para turistas y vecinos que quieren algo completo sin perder tiempo.', badge: 'Rápido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'hst1', name: 'Visitante', source: 'Google', rating: 5, text: 'Café, pastries y bocados rápidos en un ambiente cálido de Santiago.', date: '2026' },
    { id: 'hst2', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputación pública destaca servicio amable y panadería cuidada.', date: '2026' },
    { id: 'hst3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Un café pequeño con identidad clara para visitantes del centro.', date: '2026' },
  ],
  faqs: [
    { question: '¿Dónde está Hola Santiago?', answer: 'En C. 70 479A, Barrio de Santiago, Centro, Mérida, Yucatán.' },
    { question: '¿Qué ofrece?', answer: 'Café, panadería, jugos y bocados rápidos como bagels y pastries.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rápido Hola Santiago',
    messageTemplate: 'Hola Santiago. Quisiera información sobre menú o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529992335062',
  },
  whatsapp: {
    number: '529992335062',
    defaultMessage: 'Hola Santiago, quisiera información sobre menú, horario o ubicación.',
    floatingButton: true,
    ariaLabel: 'Contactar a Hola Santiago por WhatsApp',
  },
  location: {
    address: 'C. 70 479A, Barrio de Santiago, Centro',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97000',
    country: 'México',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Hola%20Santiago%20C.%2070%20479A%20Merida',
    mapAriaLabel: 'Mapa de ubicación de Hola Santiago en Mérida',
    mapImageAlt: 'Mapa referencial de Hola Santiago en Mérida',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '7:30 am - 3:00 pm' },
      { day: 'Martes', hours: '7:30 am - 3:00 pm' },
      { day: 'Miércoles', hours: '7:30 am - 3:00 pm' },
      { day: 'Jueves', hours: '7:30 am - 3:00 pm' },
      { day: 'Viernes', hours: '7:30 am - 3:00 pm' },
      { day: 'Sábado', hours: '7:30 am - 2:30 pm' },
      { day: 'Domingo', hours: 'Cerrado', closed: true },
    ],
    phone: '+52 999 233 5062',
    email: 'contacto@holasantiago.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/holasantiagomid/?hl=es',
  },
};
