import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const HOMU_MERIDA_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'homu-merida',
  name: 'Homu Merida',
  tagline: 'Fusion japonesa mexicana y bar escondido',
  category: 'bar',
  concept: 'Un concepto contemporaneo que mezcla cultura japonesa y mexicana con cocina, cocteles y el atractivo extra de Ignoto, su bar oculto.',
  identity: {
    id: 'homu-merida',
    name: 'Homu Merida',
    tagline: 'Fusion japonesa mexicana y bar escondido',
    category: 'bar',
    concept: 'Un concepto contemporaneo que mezcla cultura japonesa y mexicana con cocina, cocteles y el atractivo extra de Ignoto, su bar oculto.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.22 0.055 32)',
    accentColor: 'oklch(0.59 0.17 24)',
    bgBase: 'oklch(0.985 0.012 84)',
    darkMode: true,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'dark',
    primary: 'oklch(0.22 0.055 32)',
    primaryHover: 'oklch(0.22 0.055 32)',
    accent: 'oklch(0.59 0.17 24)',
    cta: 'oklch(0.72 0.12 88)',
    background: 'oklch(0.985 0.012 84)',
    surface: 'oklch(0.18 0.03 30)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.12 0.025 28)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Homu Merida - Fusion japonesa mexicana y bar escondido',
    description: 'Homu Merida: Un concepto contemporaneo que mezcla cultura japonesa y mexicana con cocina, cocteles y el atractivo extra de Ignoto, su bar oculto.',
    keywords: ['Homu Merida', 'Fusion japonesa mexicana y bar escondido', 'Centro, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Bar',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Homu Merida\nJapon y Mexico en una noche',
    subheadline: 'Una experiencia visual, social y nocturna para convertir curiosidad de Instagram en reservas, ubicacion y visita real.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Centro, Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.54,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Homu Merida - Centro, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Homu Merida ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Homu Merida',
      lead: 'Homu ya tiene una identidad fuerte en redes: decoracion cuidada, comida fotogenica, cocteles y la historia del bar escondido Ignoto.',
      body: 'El sitio debe hacer esa energia mas facil de vender: explicar el concepto en segundos, mostrar cocina y cocteleria, y dejar el camino a reserva o WhatsApp siempre visible.',
      foundedLabel: 'Centro, Merida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Fusion japonesa mexicana y bar escondido',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '7.5k', label: 'Seguidores IG' },
        { value: '2', label: 'Conceptos en uno' },
        { value: 'Centro', label: 'Zona de visita' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Homu Merida en Centro, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Homu Merida',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Homu Merida?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'fusion', name: 'Fusion', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'sushi-y-crudos', name: 'Sushi y crudos', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'tacos-nikkei', name: 'Tacos nikkei', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'cocteles', name: 'Cocteles', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'bar-oculto', name: 'Bar oculto', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'fusion', name: 'Tostada nikkei', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'sushi-y-crudos', name: 'Taco de pescado tempura', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'tacos-nikkei', name: 'Tiradito yuzu chile', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'cocteles', name: 'Ramen birria', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'bar-oculto', name: 'Sushi de autor', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'fusion', name: 'Gyozas de cochinita', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'sushi-y-crudos', name: 'Highball de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$160' },
    { id: 'm8', categoryId: 'tacos-nikkei', name: 'Coctel Ignoto', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$160' }
  ],
  promotions: [
    { id: 'p1', title: 'Ignoto adentro', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Noche de fusion', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=1800&auto=format&fit=crop&q=85', alt: 'Homu Merida preview image 1', caption: 'Homu Merida', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=1000&auto=format&fit=crop&q=85', alt: 'Homu Merida preview image 2', caption: 'Homu Merida', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1600&auto=format&fit=crop&q=85', alt: 'Homu Merida preview image 3', caption: 'Homu Merida', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&auto=format&fit=crop&q=80', alt: 'Homu Merida preview image 4', caption: 'Homu Merida', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=1800&auto=format&fit=crop&q=85', alt: 'Homu Merida preview image 5', caption: 'Homu Merida', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=1000&auto=format&fit=crop&q=85', alt: 'Homu Merida preview image 6', caption: 'Homu Merida', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 7.5k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Homu Merida?', answer: 'Un concepto contemporaneo que mezcla cultura japonesa y mexicana con cocina, cocteles y el atractivo extra de Ignoto, su bar oculto.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Homu Merida',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Homu Merida. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola Homu Merida, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Homu Merida por WhatsApp',
  },
  location: {
    address: 'Centro, Merida',
    city: 'Centro',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Homu%20Merida%20Centro%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Homu Merida',
    mapImageAlt: 'Mapa referencial de Homu Merida',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'contacto@homu.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/homu.mid/',
  },
};

