import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const IDILIO_FOLKLORE_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'idilio-folklore-cervecero',
  name: 'Idilio Folklore Cervecero',
  tagline: 'Cerveza artesanal y folklore yucateco',
  category: 'bar',
  concept: 'Bar y restaurante de cerveza artesanal con productores locales, cocina fusion y terraza jardin con angulo cultural y folklorico.',
  identity: {
    id: 'idilio-folklore-cervecero',
    name: 'Idilio Folklore Cervecero',
    tagline: 'Cerveza artesanal y folklore yucateco',
    category: 'bar',
    concept: 'Bar y restaurante de cerveza artesanal con productores locales, cocina fusion y terraza jardin con angulo cultural y folklorico.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.35 0.08 145)',
    accentColor: 'oklch(0.62 0.11 94)',
    bgBase: 'oklch(0.975 0.018 96)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.35 0.08 145)',
    primaryHover: 'oklch(0.35 0.08 145)',
    accent: 'oklch(0.62 0.11 94)',
    cta: 'oklch(0.7 0.14 64)',
    background: 'oklch(0.975 0.018 96)',
    surface: 'oklch(0.995 0.007 96)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.19 0.035 128)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Idilio Folklore Cervecero - Cerveza artesanal y folklore yucateco',
    description: 'Idilio Folklore Cervecero: Bar y restaurante de cerveza artesanal con productores locales, cocina fusion y terraza jardin con angulo cultural y folklorico.',
    keywords: ['Idilio Folklore Cervecero', 'Cerveza artesanal y folklore yucateco', 'Calzada de los Frailes, Valladolid', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Bar',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Idilio\nfolklore cervecero',
    subheadline: 'Un sitio con alma de Valladolid para ordenar cervezas, cocina, terraza jardin y productores locales en una experiencia memorable.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Calzada de los Frailes, Valladolid',
    backgroundImage: 'https://images.unsplash.com/photo-1532635241-17e820acc59f?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Idilio Folklore Cervecero - Calzada de los Frailes, Valladolid',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1532635241-17e820acc59f?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Idilio Folklore Cervecero ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Idilio Folklore Cervecero',
      lead: 'Idilio tiene un relato fuerte: cerveza yucateca, productores locales, comida fusion y jardin en una calle de alto paseo.',
      body: 'La web debe capturar cultura y antojo a la vez: que se entienda que es bar, restaurante, terraza y escaparate de cerveza artesanal local.',
      foundedLabel: 'Calzada de los Frailes, Valladolid',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Cerveza artesanal y folklore yucateco',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '4.1k', label: 'Seguidores IG' },
        { value: 'Local', label: 'Productores yucatecos' },
        { value: 'Frailes', label: 'Zona turistica' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Idilio Folklore Cervecero en Calzada de los Frailes, Valladolid',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Idilio Folklore Cervecero',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Idilio Folklore Cervecero?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'cervezas', name: 'Cervezas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'botanas', name: 'Botanas', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'fusion', name: 'Fusion', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'parrilla', name: 'Parrilla', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'sin-alcohol', name: 'Sin alcohol', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'cervezas', name: 'Vuelo de cervezas locales', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'botanas', name: 'IPA yucateca', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'fusion', name: 'Lager de temporada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'parrilla', name: 'Tacos de lechon', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'sin-alcohol', name: 'Hamburguesa de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'cervezas', name: 'Ceviche cervecero', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'botanas', name: 'Papas con especias', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$160' },
    { id: 'm8', categoryId: 'fusion', name: 'Agua artesanal', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$160' }
  ],
  promotions: [
    { id: 'p1', title: 'Vuelo de productores locales', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Terraza jardin', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1532635241-17e820acc59f?w=1800&auto=format&fit=crop&q=85', alt: 'Idilio Folklore Cervecero preview image 1', caption: 'Idilio Folklore Cervecero', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?w=1000&auto=format&fit=crop&q=85', alt: 'Idilio Folklore Cervecero preview image 2', caption: 'Idilio Folklore Cervecero', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=1600&auto=format&fit=crop&q=85', alt: 'Idilio Folklore Cervecero preview image 3', caption: 'Idilio Folklore Cervecero', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&auto=format&fit=crop&q=80', alt: 'Idilio Folklore Cervecero preview image 4', caption: 'Idilio Folklore Cervecero', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1532635241-17e820acc59f?w=1800&auto=format&fit=crop&q=85', alt: 'Idilio Folklore Cervecero preview image 5', caption: 'Idilio Folklore Cervecero', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1516458464372-eea4ab222b31?w=1000&auto=format&fit=crop&q=85', alt: 'Idilio Folklore Cervecero preview image 6', caption: 'Idilio Folklore Cervecero', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 4.1k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Idilio Folklore Cervecero?', answer: 'Bar y restaurante de cerveza artesanal con productores locales, cocina fusion y terraza jardin con angulo cultural y folklorico.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Idilio Folklore Cervecero',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Idilio Folklore Cervecero. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529850000000',
  },
  whatsapp: {
    number: '529850000000',
    defaultMessage: 'Hola Idilio Folklore Cervecero, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Idilio Folklore Cervecero por WhatsApp',
  },
  location: {
    address: 'Calzada de los Frailes, Valladolid',
    city: 'Calzada de los Frailes',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Idilio%20Folklore%20Cervecero%20Calzada%20de%20los%20Frailes%2C%20Valladolid',
    mapAriaLabel: 'Mapa de ubicacion de Idilio Folklore Cervecero',
    mapImageAlt: 'Mapa referencial de Idilio Folklore Cervecero',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 985 000 0000',
    email: 'hola@idiliomx.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/idiliomx/',
  },
};

