import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const LUUN_BRUNCH_COFFEE_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'luun-brunch-coffee',
  name: 'LUUN Brunch & Coffee',
  tagline: 'Brunch limpio, cafe y terraza pet friendly',
  category: 'cafe',
  concept: 'Brunch y cafe de estetica limpia en el norte de Merida, con terraza pet friendly y reservas por WhatsApp.',
  identity: {
    id: 'luun-brunch-coffee',
    name: 'LUUN Brunch & Coffee',
    tagline: 'Brunch limpio, cafe y terraza pet friendly',
    category: 'cafe',
    concept: 'Brunch y cafe de estetica limpia en el norte de Merida, con terraza pet friendly y reservas por WhatsApp.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.36 0.06 145)',
    accentColor: 'oklch(0.68 0.09 92)',
    bgBase: 'oklch(0.985 0.012 96)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.36 0.06 145)',
    primaryHover: 'oklch(0.36 0.06 145)',
    accent: 'oklch(0.68 0.09 92)',
    cta: 'oklch(0.74 0.1 74)',
    background: 'oklch(0.985 0.012 96)',
    surface: 'oklch(0.998 0.004 96)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.21 0.025 136)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'LUUN Brunch & Coffee - Brunch limpio, cafe y terraza pet friendly',
    description: 'LUUN Brunch & Coffee: Brunch y cafe de estetica limpia en el norte de Merida, con terraza pet friendly y reservas por WhatsApp.',
    keywords: ['LUUN Brunch & Coffee', 'Brunch limpio, cafe y terraza pet friendly', 'Plaza Peninsula, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'LUUN Brunch & Coffee\ncalma para el norte',
    subheadline: 'Un sitio elegante y sereno para que fotos, menu, terraza pet friendly y reservas por WhatsApp se entiendan al primer toque.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Plaza Peninsula, Prolongacion Montejo',
    backgroundImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'LUUN Brunch & Coffee - Plaza Peninsula, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'LUUN Brunch & Coffee ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor LUUN Brunch & Coffee',
      lead: 'LUUN se percibe limpio, fotografiable y de zona norte: cafe, brunch, terraza y una experiencia cuidada.',
      body: 'La oportunidad esta en pasar de Instagram a conversion: menu claro, reglas pet friendly, mapa a Plaza Peninsula y WhatsApp como accion principal.',
      foundedLabel: 'Plaza Peninsula, Prolongacion Montejo',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Brunch limpio, cafe y terraza pet friendly',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '9.0k', label: 'Seguidores IG' },
        { value: 'Pet', label: 'Terraza amigable' },
        { value: 'Norte', label: 'Ubicacion premium' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra LUUN Brunch & Coffee en Plaza Peninsula, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu LUUN Brunch & Coffee',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar LUUN Brunch & Coffee?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'brunch', name: 'Brunch', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'cafe', name: 'Cafe', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'healthy', name: 'Healthy', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'dulce', name: 'Dulce', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'pet-friendly', name: 'Pet friendly', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'brunch', name: 'Bowl de fruta y granola', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'cafe', name: 'Toast de aguacate', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm3', categoryId: 'healthy', name: 'Croissant de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm4', categoryId: 'dulce', name: 'Huevos LUUN', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm5', categoryId: 'pet-friendly', name: 'Hotcakes limpios', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm6', categoryId: 'brunch', name: 'Latte de especialidad', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm7', categoryId: 'cafe', name: 'Cold brew', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm8', categoryId: 'healthy', name: 'Snack pet friendly', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' }
  ],
  promotions: [
    { id: 'p1', title: 'Terraza pet friendly', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Reserva por WhatsApp', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1800&auto=format&fit=crop&q=85', alt: 'LUUN Brunch & Coffee preview image 1', caption: 'LUUN Brunch & Coffee', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1000&auto=format&fit=crop&q=85', alt: 'LUUN Brunch & Coffee preview image 2', caption: 'LUUN Brunch & Coffee', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1600&auto=format&fit=crop&q=85', alt: 'LUUN Brunch & Coffee preview image 3', caption: 'LUUN Brunch & Coffee', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&q=80', alt: 'LUUN Brunch & Coffee preview image 4', caption: 'LUUN Brunch & Coffee', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1800&auto=format&fit=crop&q=85', alt: 'LUUN Brunch & Coffee preview image 5', caption: 'LUUN Brunch & Coffee', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1000&auto=format&fit=crop&q=85', alt: 'LUUN Brunch & Coffee preview image 6', caption: 'LUUN Brunch & Coffee', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 9.0k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a LUUN Brunch & Coffee?', answer: 'Brunch y cafe de estetica limpia en el norte de Merida, con terraza pet friendly y reservas por WhatsApp.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido LUUN Brunch & Coffee',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola LUUN Brunch & Coffee. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola LUUN Brunch & Coffee, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a LUUN Brunch & Coffee por WhatsApp',
  },
  location: {
    address: 'Plaza Peninsula, Prolongacion Montejo',
    city: 'Plaza Peninsula',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=LUUN%20Brunch%20%26%20Coffee%20Plaza%20Peninsula%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de LUUN Brunch & Coffee',
    mapImageAlt: 'Mapa referencial de LUUN Brunch & Coffee',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'hola@luun.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/luun_mid/',
  },
};

