import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const MANJAR_BLANCO_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'manjar-blanco-merida',
  name: 'Manjar Blanco',
  tagline: 'Cocina yucateca tradicional en Santa Ana',
  category: 'restaurant',
  concept: 'Restaurante yucateco en Santa Ana con desayunos, comida regional, cochinita, queso relleno, huevos motulenos, postres y ambiente familiar.',
  identity: {
    id: 'manjar-blanco-merida',
    name: 'Manjar Blanco',
    tagline: 'Cocina yucateca tradicional en Santa Ana',
    category: 'restaurant',
    concept: 'Restaurante yucateco en Santa Ana con desayunos, comida regional, cochinita, queso relleno, huevos motulenos, postres y ambiente familiar.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.52 0.13 48)',
    accentColor: 'oklch(0.66 0.12 92)',
    bgBase: 'oklch(0.98 0.015 75)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.52 0.13 48)',
    primaryHover: 'oklch(0.44 0.13 48)',
    accent: 'oklch(0.66 0.12 92)',
    cta: 'oklch(0.53 0.16 30)',
    background: 'oklch(0.98 0.015 75)',
    surface: 'oklch(0.996 0.008 75)',
    surfaceAlt: 'oklch(0.94 0.03 72)',
    border: 'oklch(0.84 0.028 70)',
    text: 'oklch(0.23 0.032 54)',
    textMuted: 'oklch(0.43 0.03 54)',
    radius: 'classic',
  },
  seo: {
    title: 'Manjar Blanco Merida - Cocina yucateca',
    description: 'Manjar Blanco en Merida: comida yucateca tradicional, desayunos, cochinita, huevos motulenos, queso relleno y postres en Santa Ana.',
    keywords: ['manjar blanco merida', 'comida yucateca merida', 'santa ana merida restaurante', 'huevos motulenos merida', 'cochinita merida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Manjar Blanco\nsabor yucateco en Santa Ana',
    subheadline: 'Desayunos, cocina regional, cochinita, huevos motulenos y postres en una experiencia movil clara para visitantes y locales.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Santa Ana, Centro de Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.28,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escribir',
    stickyLabel: 'Menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Manjar Blanco - Merida, Yucatan',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Comida mexicana tradicional servida en mesa',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Santa Ana',
      heading: 'Una cocina yucateca con alta confianza necesita un sitio directo',
      lead: 'Los listados publicos destacan comida yucateca, desayunos, cochinita pibil, huevos motulenos, queso relleno y un volumen alto de resenas.',
      body: 'El sitio ordena esa reputacion en secciones que ayudan a decidir: que pedir, donde esta, a que hora abre y como contactar sin perderse entre mapas y redes.',
      foundedLabel: 'Calle 47',
    },
    menuHighlights: {
      eyebrow: 'Favoritos yucatecos',
      heading: 'Huevos motulenos, cochinita, queso relleno y postres',
      subheading: 'Una carta regional que se beneficia de categorias claras, precios visibles y acceso rapido a ubicacion.',
      fullMenuLabel: 'Explorar menu',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Tradicion yucateca con muchas senales de confianza',
      subheading: 'Las fuentes publicas lo muestran como restaurante verificado, con miles de resenas y alta intencion de visita.',
      proofItems: [
        { value: '4.5', label: 'Rating Google' },
        { value: '3k+', label: 'Resenas visibles' },
        { value: '8:00', label: 'Apertura diaria' },
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Manjar Blanco frente al mercado de Santa Ana',
    },
    menuPage: {
      eyebrow: 'Yucateco tradicional',
      heading: 'Menu Manjar Blanco',
      lead: 'Desayunos, comida regional, antojitos, platos yucatecos y postres de la casa.',
      finalHeading: 'Listo para visitar Manjar Blanco?',
      finalDescription: 'Menu, mapa, horario y telefono quedan a un toque.',
    },
  },
  menuCategories: [
    { id: 'desayunos', name: 'Desayunos', description: 'Para empezar el dia en Santa Ana' },
    { id: 'yucatecos', name: 'Yucatecos', description: 'Platos regionales de la casa' },
    { id: 'antojitos', name: 'Antojitos', description: 'Panuchos, salbutes y tacos' },
    { id: 'postres', name: 'Postres', description: 'Dulces y cierre regional' },
    { id: 'bebidas', name: 'Bebidas', description: 'Aguas y bebidas frescas' },
  ],
  menuItems: [
    { id: 'mb1', categoryId: 'desayunos', name: 'Huevos motulenos', description: 'Clasico yucateco con huevo, tortilla, frijol, jamon, chícharos y salsa.', price: '$165', tag: 'signature', featured: true },
    { id: 'mb2', categoryId: 'desayunos', name: 'Chilaquiles verdes', description: 'Chilaquiles con salsa verde y acompanamientos.', price: '$155', featured: true },
    { id: 'mb3', categoryId: 'yucatecos', name: 'Cochinita pibil', description: 'Cerdo marinado con achiote, cebolla morada y tortillas.', price: '$210', tag: 'popular', featured: true },
    { id: 'mb4', categoryId: 'yucatecos', name: 'Queso relleno', description: 'Especialidad regional con salsa y guiso.', price: '$230', featured: true },
    { id: 'mb5', categoryId: 'yucatecos', name: 'Relleno negro', description: 'Plato yucateco intenso y tradicional.', price: '$220' },
    { id: 'mb6', categoryId: 'antojitos', name: 'Panuchos surtidos', description: 'Antojitos yucatecos para compartir.', price: '$135' },
    { id: 'mb7', categoryId: 'postres', name: 'Manjar blanco', description: 'Postre de la casa que da nombre al restaurante.', price: '$95' },
    { id: 'mb8', categoryId: 'bebidas', name: 'Agua de chaya', description: 'Bebida fresca regional.', price: '$55' },
  ],
  promotions: [
    { id: 'mbp1', title: 'Desayuno yucateco', description: 'Huevos motulenos y chilaquiles como ganchos de primera visita.', badge: 'Desayuno', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'mbp2', title: 'Comida regional', description: 'Cochinita, queso relleno y antojitos con direccion visible.', badge: 'Regional', ctaLabel: 'Llamar', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'mbt1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputacion publica destaca cocina yucateca, desayunos y ambiente familiar.', date: '2026' },
    { id: 'mbt2', name: 'Visitante', source: 'TripAdvisor', rating: 5, text: 'Una opcion reconocida para probar platos regionales cerca de Santa Ana.', date: '2026' },
    { id: 'mbt3', name: 'Perfil publico', source: 'Direct', rating: 5, text: 'La carta tradicional gana claridad cuando el menu, mapa y telefono estan juntos.', date: '2026' },
  ],
  faqs: [
    { question: 'Que ofrece Manjar Blanco?', answer: 'Cocina yucateca tradicional, desayunos, huevos motulenos, cochinita, queso relleno, antojitos y postres.' },
    { question: 'Donde esta ubicado?', answer: 'En Calle 47 496, entre 58 y 60, frente al Parque y Mercado de Santa Ana.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Manjar Blanco',
    messageTemplate: 'Hola Manjar Blanco. Quisiera informacion sobre menu o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529995476237',
  },
  whatsapp: {
    number: '529995476237',
    defaultMessage: 'Hola Manjar Blanco, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Manjar Blanco por WhatsApp',
  },
  location: {
    address: 'Calle 47 496, entre 58 y 60, Santa Ana, Centro',
    city: 'Merida',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Manjar%20Blanco%20Calle%2047%20496%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Manjar Blanco en Merida',
    mapImageAlt: 'Mapa referencial de Manjar Blanco en Merida',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '8:00 am - 6:00 pm' },
      { day: 'Martes', hours: '8:00 am - 6:00 pm' },
      { day: 'Miercoles', hours: '8:00 am - 6:00 pm' },
      { day: 'Jueves', hours: '8:00 am - 6:00 pm' },
      { day: 'Viernes', hours: '8:00 am - 6:00 pm' },
      { day: 'Sabado', hours: '8:00 am - 6:00 pm' },
      { day: 'Domingo', hours: '8:00 am - 6:00 pm' },
    ],
    phone: '+52 999 547 6237',
  },
  social: {
    facebook: 'https://www.facebook.com/elmanjarblanco/',
  },
};
