import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const MATIN_MERIDA_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'matin-merida',
  name: 'Matin',
  tagline: 'Cocinando con amor en Garcia Lavin',
  category: 'restaurant',
  concept: 'Cocina mexicana contemporanea y desayunos con tono hogareno, calido e intimo bajo la idea Cocinando con amor.',
  identity: {
    id: 'matin-merida',
    name: 'Matin',
    tagline: 'Cocinando con amor en Garcia Lavin',
    category: 'restaurant',
    concept: 'Cocina mexicana contemporanea y desayunos con tono hogareno, calido e intimo bajo la idea Cocinando con amor.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.47 0.1 48)',
    accentColor: 'oklch(0.62 0.1 105)',
    bgBase: 'oklch(0.984 0.018 82)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.47 0.1 48)',
    primaryHover: 'oklch(0.47 0.1 48)',
    accent: 'oklch(0.62 0.1 105)',
    cta: 'oklch(0.73 0.12 71)',
    background: 'oklch(0.984 0.018 82)',
    surface: 'oklch(0.998 0.006 82)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.24 0.04 54)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Matin - Cocinando con amor en Garcia Lavin',
    description: 'Matin: Cocina mexicana contemporanea y desayunos con tono hogareno, calido e intimo bajo la idea Cocinando con amor.',
    keywords: ['Matin', 'Cocinando con amor en Garcia Lavin', 'Garcia Lavin, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Matin\ncocina con amor diario',
    subheadline: 'Una presencia web cercana para explicar desayunos, comida casera, horario corrido y contacto en Garcia Lavin.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Av. Garcia Lavin, Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Matin - Garcia Lavin, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Matin ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1625166914826-efd23e379d7a?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Matin',
      lead: 'Matin no necesita sonar enorme: su fuerza esta en lo cercano, casero y consistente, abierto todos los dias de 8 a 5.',
      body: 'El sitio debe sentirse de barrio pero pulido: confianza, menu sencillo, horario visible y contacto directo para una marca en etapa temprana.',
      foundedLabel: 'Av. Garcia Lavin, Merida',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Cocinando con amor en Garcia Lavin',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '8-5', label: 'Horario diario' },
        { value: '3.8k', label: 'Seguidores IG' },
        { value: 'Barrio', label: 'Trato cercano' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Matin en Garcia Lavin, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Matin',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Matin?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'desayunos', name: 'Desayunos', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'mexicano', name: 'Mexicano', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'de-casa', name: 'De casa', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'cafe', name: 'Cafe', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'postres', name: 'Postres', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'desayunos', name: 'Huevos de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'mexicano', name: 'Chilaquiles Matin', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm3', categoryId: 'de-casa', name: 'Enfrijoladas suaves', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm4', categoryId: 'cafe', name: 'Tostada de aguacate', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220', featured: true },
    { id: 'm5', categoryId: 'postres', name: 'Sopa del dia', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm6', categoryId: 'desayunos', name: 'Milanesa casera', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm7', categoryId: 'mexicano', name: 'Cafe de olla', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' },
    { id: 'm8', categoryId: 'de-casa', name: 'Pan dulce del dia', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$220' }
  ],
  promotions: [
    { id: 'p1', title: 'Cocinando con amor', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Abierto todos los dias', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85', alt: 'Matin preview image 1', caption: 'Matin', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1000&auto=format&fit=crop&q=85', alt: 'Matin preview image 2', caption: 'Matin', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1625166914826-efd23e379d7a?w=1600&auto=format&fit=crop&q=85', alt: 'Matin preview image 3', caption: 'Matin', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80', alt: 'Matin preview image 4', caption: 'Matin', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85', alt: 'Matin preview image 5', caption: 'Matin', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1000&auto=format&fit=crop&q=85', alt: 'Matin preview image 6', caption: 'Matin', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 3.8k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Matin?', answer: 'Cocina mexicana contemporanea y desayunos con tono hogareno, calido e intimo bajo la idea Cocinando con amor.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Matin',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Matin. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola Matin, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Matin por WhatsApp',
  },
  location: {
    address: 'Av. Garcia Lavin, Merida',
    city: 'Garcia Lavin',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Matin%20Garcia%20Lavin%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Matin',
    mapImageAlt: 'Mapa referencial de Matin',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'hola@matinmerida.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/matin.merida/',
  },
};

