import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const PANCHO_MAIZ_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'pancho-maiz-merida',
  name: 'Pancho Maiz',
  tagline: 'Maiz criollo, desayunos y cocina de milpa',
  category: 'restaurant',
  concept: 'Nixtamaleria y antojeria en Mejorada enfocada en maiz criollo, productos locales, desayunos, antojitos y cocina mexicana contemporanea.',
  identity: {
    id: 'pancho-maiz-merida',
    name: 'Pancho Maiz',
    tagline: 'Maiz criollo, desayunos y cocina de milpa',
    category: 'restaurant',
    concept: 'Nixtamaleria y antojeria en Mejorada enfocada en maiz criollo, productos locales, desayunos, antojitos y cocina mexicana contemporanea.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.57 0.13 76)',
    accentColor: 'oklch(0.68 0.14 118)',
    bgBase: 'oklch(0.98 0.018 86)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.57 0.13 76)',
    primaryHover: 'oklch(0.48 0.13 76)',
    accent: 'oklch(0.68 0.14 118)',
    cta: 'oklch(0.52 0.14 43)',
    background: 'oklch(0.98 0.018 86)',
    surface: 'oklch(0.996 0.008 86)',
    surfaceAlt: 'oklch(0.94 0.036 92)',
    border: 'oklch(0.83 0.035 88)',
    text: 'oklch(0.23 0.035 70)',
    textMuted: 'oklch(0.43 0.032 70)',
    radius: 'classic',
  },
  seo: {
    title: 'Pancho Maiz Merida - Maiz criollo y desayunos',
    description: 'Pancho Maiz en Merida: nixtamaleria, cocina de maiz criollo, desayunos, antojitos y productos locales cerca del Parque de Mejorada.',
    keywords: ['pancho maiz', 'maiz criollo merida', 'desayunos merida', 'antojeria merida', 'mejorada merida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Pancho Maiz\nel alma del campo',
    subheadline: 'Maiz criollo, tortillas, antojitos y desayunos con producto local en una experiencia clara para visitar o pedir informacion.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Parque de Mejorada, Merida',
    backgroundImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.28,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escribir',
    stickyLabel: 'Menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Pancho Maiz - Merida, Yucatan',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1624381898411-846e7d193883?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Tortillas y maiz servidos en mesa mexicana',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Maiz criollo',
      heading: 'Un concepto con historia que merece ordenarse desde el primer toque',
      lead: 'La informacion publica lo presenta como comedor y nixtamaleria dedicada a rescatar, transformar y difundir el maiz nativo de la peninsula.',
      body: 'El sitio convierte esa historia en una experiencia movil directa: menu, horarios, direccion, redes y contacto sin obligar al cliente a buscar entre publicaciones.',
      foundedLabel: 'Mejorada',
    },
    menuHighlights: {
      eyebrow: 'Menu de milpa',
      heading: 'Desayunos, tortillas, antojitos y pan dulce',
      subheading: 'Una carta visual para comunicar maiz criollo, productos regionales y platos de temporada con mucha claridad.',
      fullMenuLabel: 'Explorar menu',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Un favorito local con identidad muy clara',
      subheading: 'Las referencias publicas destacan maiz nativo, cocina mexicana, opciones veganas y una propuesta con alma de campo.',
      proofItems: [
        { value: '4.5', label: 'Rating publico' },
        { value: '900+', label: 'Resenas visibles' },
        { value: '9:00', label: 'Apertura publicada' },
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Pancho Maiz cerca del Parque de Mejorada',
    },
    menuPage: {
      eyebrow: 'Maiz + desayuno',
      heading: 'Menu Pancho Maiz',
      lead: 'Platillos alrededor del maiz criollo, desayunos, antojitos, bebidas y opciones de temporada.',
      finalHeading: 'Listo para visitar Pancho Maiz?',
      finalDescription: 'Menu, mapa, horario y contacto quedan a un toque.',
    },
  },
  menuCategories: [
    { id: 'desayunos', name: 'Desayunos', description: 'Platos de manana con producto local' },
    { id: 'maiz', name: 'Maiz criollo', description: 'Tortillas, sopes, huaraches y masa' },
    { id: 'antojitos', name: 'Antojitos', description: 'Quesadillas, gorditas y tacos' },
    { id: 'dulce', name: 'Dulce', description: 'Pan y postres de temporada' },
    { id: 'bebidas', name: 'Bebidas', description: 'Cafe, aguas y bebidas frescas' },
  ],
  menuItems: [
    { id: 'pm1', categoryId: 'desayunos', name: 'Plato de fruta', description: 'Fruta de temporada, yogurt de miel floral y granola.', price: '$145', featured: true },
    { id: 'pm2', categoryId: 'desayunos', name: 'French toast', description: 'Cremoso de lima, miel de flores y fruta.', price: '$175', tag: 'popular', featured: true },
    { id: 'pm3', categoryId: 'maiz', name: 'Sope jumbo de maiz criollo', description: 'Maiz criollo, guiso, quesito fresco y crema acida.', price: '$185', tag: 'signature', featured: true },
    { id: 'pm4', categoryId: 'maiz', name: 'Huarache de chorizo verde', description: 'Maiz, papas doradas, nopalitos y queso fresco.', price: '$190' },
    { id: 'pm5', categoryId: 'antojitos', name: 'Quesadilla chata', description: 'Huitlacoche, quesillo y salsa taquera.', price: '$155', featured: true },
    { id: 'pm6', categoryId: 'antojitos', name: 'Gordita de harina', description: 'Rajas, elote tierno y quesillo de Sucila.', price: '$160' },
    { id: 'pm7', categoryId: 'dulce', name: 'Panque de elote', description: 'Pan de maiz con caramelo salado.', price: '$95' },
    { id: 'pm8', categoryId: 'bebidas', name: 'Horchata latte', description: 'Cafe y horchata para una bebida fresca de casa.', price: '$85' },
  ],
  promotions: [
    { id: 'pmp1', title: 'Mesa de maiz criollo', description: 'Una entrada perfecta para explicar la propuesta de milpa y temporada.', badge: 'Maiz', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'pmp2', title: 'Desayuno en Mejorada', description: 'Horario corto, menu visual y contacto rapido para decidir temprano.', badge: 'Manana', ctaLabel: 'Escribir', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'pmt1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La propuesta publica destaca maiz criollo, tortillas y cocina mexicana con producto local.', date: '2026' },
    { id: 'pmt2', name: 'Visitante', source: 'Instagram', rating: 5, text: 'Un concepto con identidad fuerte que se entiende mejor con un menu propio.', date: '2026' },
    { id: 'pmt3', name: 'Perfil publico', source: 'Direct', rating: 5, text: 'Desayunos, antojitos y opciones vegetales son categorias ideales para explorar desde movil.', date: '2026' },
  ],
  faqs: [
    { question: 'Que ofrece Pancho Maiz?', answer: 'Cocina mexicana alrededor del maiz criollo, desayunos, tortillas, antojitos, pan y bebidas.' },
    { question: 'Donde esta ubicado?', answer: 'En Calle 59 437a, Parque de la Mejorada, Centro, Merida, Yucatan.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Pancho Maiz',
    messageTemplate: 'Hola Pancho Maiz. Quisiera informacion sobre menu o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529997503589',
  },
  whatsapp: {
    number: '529997503589',
    defaultMessage: 'Hola Pancho Maiz, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Pancho Maiz por WhatsApp',
  },
  location: {
    address: 'Calle 59 437a, Parque de la Mejorada, Centro',
    city: 'Merida',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pancho%20Maiz%20Calle%2059%20437a%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Pancho Maiz en Merida',
    mapImageAlt: 'Mapa referencial de Pancho Maiz en Merida',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '9:00 am - 4:00 pm' },
      { day: 'Martes', hours: '9:00 am - 4:00 pm' },
      { day: 'Miercoles', hours: '9:00 am - 4:00 pm' },
      { day: 'Jueves', hours: '9:00 am - 4:00 pm' },
      { day: 'Viernes', hours: '9:00 am - 4:00 pm' },
      { day: 'Sabado', hours: '8:00 am - 3:00 pm' },
      { day: 'Domingo', hours: 'Cerrado', closed: true },
    ],
    phone: '+52 999 750 3589',
    email: 'panchomaizmid@outlook.com',
  },
  social: {
    instagram: 'https://www.instagram.com/panchomaiz/',
    facebook: 'https://www.facebook.com/Pancho-Maiz/',
  },
};
