import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const RAMIRO_COCINA_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'ramiro-cocina-merida',
  name: 'Ramiro Cocina',
  tagline: 'Cocina mexicana de temporada en Paseo Montejo',
  category: 'restaurant',
  concept: 'Restaurante mexicano de tradicion familiar con menu de temporada, moles, molotes, quesabirria, opciones vegetales y patio en el centro de Merida.',
  identity: {
    id: 'ramiro-cocina-merida',
    name: 'Ramiro Cocina',
    tagline: 'Cocina mexicana de temporada en Paseo Montejo',
    category: 'restaurant',
    concept: 'Restaurante mexicano de tradicion familiar con menu de temporada, moles, molotes, quesabirria, opciones vegetales y patio en el centro de Merida.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.48 0.11 136)',
    accentColor: 'oklch(0.69 0.13 72)',
    bgBase: 'oklch(0.97 0.016 102)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.48 0.11 136)',
    primaryHover: 'oklch(0.4 0.11 136)',
    accent: 'oklch(0.69 0.13 72)',
    cta: 'oklch(0.52 0.13 38)',
    background: 'oklch(0.97 0.016 102)',
    surface: 'oklch(0.996 0.006 102)',
    surfaceAlt: 'oklch(0.93 0.034 118)',
    border: 'oklch(0.82 0.034 112)',
    text: 'oklch(0.22 0.034 112)',
    textMuted: 'oklch(0.42 0.032 112)',
    radius: 'soft',
  },
  seo: {
    title: 'Ramiro Cocina Merida - Cocina mexicana de temporada',
    description: 'Ramiro Cocina en Merida: cocina mexicana familiar, moles, molotes, quesabirria, opciones vegetarianas y patio cerca de Paseo Montejo.',
    keywords: ['ramiro cocina merida', 'cocina mexicana merida', 'paseo montejo restaurante', 'moles merida', 'quesabirria merida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Ramiro Cocina\ntemporada y patio en Merida',
    subheadline: 'Moles, molotes, quesabirria, productos locales y cocina de temporada en una experiencia movil lista para reservar o visitar.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Paseo Montejo, Centro',
    backgroundImage: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.28,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'Escribir',
    stickyLabel: 'Menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Ramiro Cocina - Merida, Yucatan',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Mesa de restaurante con platos mexicanos de temporada',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Temporada local',
      heading: 'Una cocina con menu cambiante necesita una experiencia clara',
      lead: 'Las referencias publicas describen una cocina mexicana familiar con producto local, opciones vegetarianas, patio y platos como moles con molote y quesabirria.',
      body: 'El prototipo organiza esa propuesta en un sitio directo para explicar el concepto, mostrar favoritos, facilitar reserva/contacto y ubicar el patio sin friccion.',
      foundedLabel: 'Paseo Montejo',
    },
    menuHighlights: {
      eyebrow: 'Menu de temporada',
      heading: 'Moles, molotes, quesabirria y cocina vegetal',
      subheading: 'Un menu corto y cambiante se entiende mejor con secciones vivas, fotos y CTAs de contacto.',
      fullMenuLabel: 'Explorar menu',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Patio, producto local y buena reputacion de comida',
      subheading: 'Las fuentes publicas destacan el ambiente, el servicio y el perfil de cocina mexicana contemporanea.',
      proofItems: [
        { value: '4.5', label: 'Rating Google' },
        { value: '370', label: 'Resenas visibles' },
        { value: '12:00', label: 'Servicio entre semana' },
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Ramiro Cocina cerca de Paseo Montejo',
    },
    menuPage: {
      eyebrow: 'Mexicano de temporada',
      heading: 'Menu Ramiro Cocina',
      lead: 'Moles, molotes, quesabirria, opciones vegetarianas, bebidas de temporada y platos para compartir.',
      finalHeading: 'Listo para visitar Ramiro Cocina?',
      finalDescription: 'Menu, mapa, horario y contacto quedan a un toque.',
    },
  },
  menuCategories: [
    { id: 'temporada', name: 'Temporada', description: 'Platos que cambian con producto local' },
    { id: 'moles', name: 'Moles', description: 'Moles, molotes y sabores de casa' },
    { id: 'tacos', name: 'Tacos', description: 'Quesabirria y antojos' },
    { id: 'vegetal', name: 'Vegetal', description: 'Opciones vegetarianas y veganas' },
    { id: 'bebidas', name: 'Bebidas', description: 'Aguas y cocteles frescos' },
  ],
  menuItems: [
    { id: 'rc1', categoryId: 'moles', name: 'Moles con molote', description: 'Molote de platano con moles de la casa.', price: '$240', tag: 'signature', featured: true },
    { id: 'rc2', categoryId: 'tacos', name: 'Quesabirria', description: 'Tacos de birria con queso, consome y salsas.', price: '$230', tag: 'popular', featured: true },
    { id: 'rc3', categoryId: 'temporada', name: 'Tostada de cactus', description: 'Tostada fresca con ingredientes de temporada.', price: '$180', featured: true },
    { id: 'rc4', categoryId: 'vegetal', name: 'Tacos de berenjena', description: 'Berenjena preparada con salsas y hierbas frescas.', price: '$190' },
    { id: 'rc5', categoryId: 'moles', name: 'Mole verde', description: 'Mole verde con proteina de temporada.', price: '$260', featured: true },
    { id: 'rc6', categoryId: 'temporada', name: 'Papadzules de camaron', description: 'Version de temporada inspirada en cocina regional.', price: '$260' },
    { id: 'rc7', categoryId: 'bebidas', name: 'Agua fresca de temporada', description: 'Bebida natural segun disponibilidad.', price: '$65' },
    { id: 'rc8', categoryId: 'bebidas', name: 'Mezcalita de la casa', description: 'Coctel fresco para patio y comida de tarde.', price: '$150' },
  ],
  promotions: [
    { id: 'rcp1', title: 'Patio de temporada', description: 'Un CTA claro para reservar o llegar al patio sin friccion.', badge: 'Patio', ctaLabel: 'Como llegar', ctaAction: 'link', ctaValue: '/contacto' },
    { id: 'rcp2', title: 'Moles y molotes', description: 'Los platos con mayor personalidad como gancho visual del sitio.', badge: 'Casa', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
  ],
  testimonials: [
    { id: 'rct1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputacion publica destaca comida mexicana creativa, patio y platos de temporada.', date: '2026' },
    { id: 'rct2', name: 'Visitante', source: 'Direct', rating: 5, text: 'Un concepto ideal para explicar menu cambiante y reservas desde movil.', date: '2026' },
    { id: 'rct3', name: 'Perfil publico', source: 'Instagram', rating: 5, text: 'Moles, quesabirria y opciones vegetales necesitan una presentacion clara y visual.', date: '2026' },
  ],
  faqs: [
    { question: 'Que ofrece Ramiro Cocina?', answer: 'Cocina mexicana de temporada, moles, molotes, quesabirria, opciones vegetarianas, bebidas y patio.' },
    { question: 'Donde esta ubicado?', answer: 'En Calle 41 x 58 y 60, Paseo Montejo 386 D, Centro, Merida.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Ramiro Cocina',
    messageTemplate: 'Hola Ramiro Cocina. Quisiera informacion sobre menu o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529992320608',
  },
  whatsapp: {
    number: '529992320608',
    defaultMessage: 'Hola Ramiro Cocina, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Ramiro Cocina por WhatsApp',
  },
  location: {
    address: 'Calle 41 x 58 y 60, Paseo Montejo 386 D, Centro',
    city: 'Merida',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ramiro%20Cocina%20Paseo%20Montejo%20386%20D%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Ramiro Cocina en Merida',
    mapImageAlt: 'Mapa referencial de Ramiro Cocina en Merida',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: 'Cerrado', closed: true },
      { day: 'Martes', hours: '12:00 pm - 6:30 pm' },
      { day: 'Miercoles', hours: '12:00 pm - 6:30 pm' },
      { day: 'Jueves', hours: '12:00 pm - 6:30 pm' },
      { day: 'Viernes', hours: '12:00 pm - 6:30 pm' },
      { day: 'Sabado', hours: '12:00 pm - 6:30 pm' },
      { day: 'Domingo', hours: '11:00 am - 3:30 pm' },
    ],
    phone: '+52 999 232 0608',
  },
  social: {
    instagram: 'https://www.instagram.com/ramirococina_/',
  },
};
