import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const SUSHI_ROLLER_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'sushi-roller-merida',
  name: 'Sushi Roller',
  tagline: 'Sushi, rolls y cocina japonesa casual',
  category: 'restaurant',
  concept: 'Restaurante japonés casual en Mérida con sushi, rolls, takeout, delivery y servicio nocturno.',
  identity: {
    id: 'sushi-roller-merida',
    name: 'Sushi Roller',
    tagline: 'Sushi, rolls y cocina japonesa casual',
    category: 'restaurant',
    concept: 'Restaurante japonés casual en Mérida con sushi, rolls, takeout, delivery y servicio nocturno.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.36 0.08 260)',
    accentColor: 'oklch(0.62 0.2 28)',
    bgBase: 'oklch(0.13 0.018 260)',
    darkMode: true,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'dark',
    primary: 'oklch(0.72 0.12 245)',
    primaryHover: 'oklch(0.78 0.13 245)',
    accent: 'oklch(0.66 0.2 28)',
    cta: 'oklch(0.62 0.2 28)',
    background: 'oklch(0.13 0.018 260)',
    surface: 'oklch(0.18 0.022 260)',
    surfaceAlt: 'oklch(0.23 0.028 260)',
    border: 'oklch(0.34 0.035 260)',
    text: 'oklch(0.96 0.006 250)',
    textMuted: 'oklch(0.76 0.02 250)',
    textInverse: 'oklch(0.12 0.018 260)',
    radius: 'sharp',
    shadow: 'high',
    motionIntensity: 'expressive',
  },
  seo: {
    title: 'Sushi Roller Mérida - Sushi y rolls',
    description: 'Sushi Roller en Mérida: sushi, rolls, comida japonesa casual, takeout y delivery.',
    keywords: ['sushi roller mérida', 'sushi mérida', 'rolls mérida', 'comida japonesa mérida', 'delivery sushi mérida'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'Restaurant',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Sushi Roller\nrolls con carácter en Mérida',
    subheadline: 'Sushi, rolls, takeout y delivery en una experiencia móvil más visual, moderna y fácil de pedir.',
    ctaLabel: 'Ver menú',
    ctaSecondaryLabel: 'Ubicación',
    locationLabel: 'C. 42 398, Mérida',
    backgroundImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.58,
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Rollos de sushi servidos en plato oscuro',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=1600&auto=format&fit=crop&q=85',
    },
    concept: {
      eyebrow: 'Sushi casual',
      heading: 'Una marca de rolls que puede verse mucho más apetecible',
      lead: 'La información pública confirma comida japonesa, sushi, rolls, takeout, delivery y horario de tarde-noche.',
      body: 'El sitio enfatiza fotografía, contraste y categorías directas para transformar búsquedas de delivery en pedidos o visitas.',
      foundedLabel: 'Mérida',
    },
    menuHighlights: {
      eyebrow: 'Rolls destacados',
      heading: 'Sushi, empanizados, ramen y bebidas frescas',
      subheading: 'Una carta visual para quien decide rápido: rolls, entradas, platos calientes y opciones para llevar.',
      fullMenuLabel: 'Explorar menú',
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Buen rating y fuerte intención de pedido',
      subheading: 'Los listados públicos destacan sushi, rolls, delivery, takeout y atención positiva.',
      proofItems: [
        { value: '4.4', label: 'Rating Google' },
        { value: '779', label: 'Reseñas visibles' },
        { value: '10', label: 'Top sushi local' },
      ],
    },
    location: {
      eyebrow: 'Ubicación',
      heading: 'Encuentra Sushi Roller en Mérida',
    },
    menuPage: {
      eyebrow: 'Sushi + delivery',
      heading: 'Menú Sushi Roller',
      lead: 'Rolls, sushi, entradas japonesas, ramen, postres y bebidas para comer ahí o pedir para llevar.',
      finalHeading: '¿Listo para pedir Sushi Roller?',
      finalDescription: 'Menú, horario, ubicación e Instagram quedan a un toque.',
    },
  },
  menuCategories: [
    { id: 'rolls', name: 'Rolls', description: 'Rollos clásicos y especiales' },
    { id: 'sushi', name: 'Sushi', description: 'Piezas, nigiri y combinados' },
    { id: 'calientes', name: 'Calientes', description: 'Ramen, pollo y arroz' },
    { id: 'postres', name: 'Postres', description: 'Gelato y antojos dulces' },
    { id: 'bebidas', name: 'Bebidas', description: 'Limonadas y bebidas frescas' },
  ],
  menuItems: [
    { id: 'sr1', categoryId: 'rolls', name: 'Roll empanizado', description: 'Roll crujiente inspirado en menciones públicas del menú.', price: '$150', tag: 'popular', featured: true },
    { id: 'sr2', categoryId: 'rolls', name: 'Roll de salmón', description: 'Salmón, arroz y salsa de la casa.', price: '$165', featured: true },
    { id: 'sr3', categoryId: 'sushi', name: 'Sushi mixto', description: 'Selección de piezas para compartir.', price: '$210', tag: 'signature', featured: true },
    { id: 'sr4', categoryId: 'sushi', name: 'Nigiri de anguila', description: 'Pieza de anguila con arroz sazonado.', price: '$95' },
    { id: 'sr5', categoryId: 'calientes', name: 'Ramen de pollo', description: 'Caldo caliente con pollo, fideos y toppings.', price: '$155' },
    { id: 'sr6', categoryId: 'calientes', name: 'Yakimeshi', description: 'Arroz salteado con verduras y proteína.', price: '$135' },
    { id: 'sr7', categoryId: 'postres', name: 'Gelato', description: 'Postre frío mencionado en reseñas públicas.', price: '$85' },
    { id: 'sr8', categoryId: 'bebidas', name: 'Limonada', description: 'Bebida fresca para acompañar rolls.', price: '$55' },
  ],
  promotions: [
    { id: 'srp1', title: 'Rolls para compartir', description: 'Una entrada visual fuerte para convertir visitas nocturnas y pedidos.', badge: 'Popular', ctaLabel: 'Ver menú', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'srp2', title: 'Takeout y delivery', description: 'CTAs pensados para resolver pedido desde móvil sin abrir varias apps.', badge: 'Para llevar', ctaLabel: 'Escribir', ctaAction: 'whatsapp' },
  ],
  testimonials: [
    { id: 'srt1', name: 'Cliente local', source: 'Google', rating: 5, text: 'La reputación pública destaca sushi fresco, rolls y servicio atento.', date: '2026' },
    { id: 'srt2', name: 'Pedido para llevar', source: 'Google', rating: 5, text: 'Un concepto ideal para convertir búsquedas de delivery en pedidos directos.', date: '2026' },
    { id: 'srt3', name: 'Perfil público', source: 'Instagram', rating: 5, text: 'Sushi Roller tiene una categoría visual fuerte que merece un sitio más apetecible.', date: '2026' },
  ],
  faqs: [
    { question: '¿Sushi Roller ofrece delivery?', answer: 'Los listados públicos indican delivery y comida para llevar.' },
    { question: '¿Cuál es el horario publicado?', answer: 'Abre todos los días desde la 1:00 pm; viernes y sábado hasta las 10:30 pm según el listado consultado.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    maxGuests: 10,
    timeSlots: ['13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00'],
    modalTitle: 'Contacto rápido Sushi Roller',
    messageTemplate: 'Hola Sushi Roller. Quisiera información sobre menú, pedido o visita para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529994320221',
  },
  whatsapp: {
    number: '529994320221',
    defaultMessage: 'Hola Sushi Roller, quisiera información sobre menú, pedido u horario.',
    floatingButton: true,
    ariaLabel: 'Contactar a Sushi Roller por WhatsApp',
  },
  location: {
    address: 'C. 42 398',
    city: 'Mérida',
    state: 'Yucatán',
    zip: '97000',
    country: 'México',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sushi%20Roller%20C.%2042%20398%20Merida',
    mapAriaLabel: 'Mapa de ubicación de Sushi Roller en Mérida',
    mapImageAlt: 'Mapa referencial de Sushi Roller en Mérida',
    openMapsLabel: 'Abrir ubicación',
    hoursTitle: 'Horario publicado',
    hours: [
      { day: 'Lunes', hours: '1:00 pm - 10:00 pm' },
      { day: 'Martes', hours: '1:00 pm - 10:00 pm' },
      { day: 'Miércoles', hours: '1:00 pm - 10:00 pm' },
      { day: 'Jueves', hours: '1:00 pm - 10:00 pm' },
      { day: 'Viernes', hours: '1:00 pm - 10:30 pm' },
      { day: 'Sábado', hours: '1:00 pm - 10:30 pm' },
      { day: 'Domingo', hours: '1:00 pm - 10:00 pm' },
    ],
    phone: '+52 999 432 0221',
    email: 'contacto@sushiroller.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/sushirollermid/',
    facebook: 'https://www.facebook.com/',
  },
};
