import { BusinessConfig } from '../business.config';
import { COFFEE_ST_FITZ_CONFIG } from './coffee-st-fitz.config';

export const VIVA_LA_BRUNCH_CONFIG: BusinessConfig = {
  ...COFFEE_ST_FITZ_CONFIG,
  id: 'viva-la-brunch',
  name: 'Viva La Brunch',
  tagline: 'Brunch colorido en Garcia Lavin',
  category: 'cafe',
  concept: 'Brunch colorido, de terraza y experiencia social, con posicionamiento Vive la experiencia y fuerte estrategia de reels.',
  identity: {
    id: 'viva-la-brunch',
    name: 'Viva La Brunch',
    tagline: 'Brunch colorido en Garcia Lavin',
    category: 'cafe',
    concept: 'Brunch colorido, de terraza y experiencia social, con posicionamiento Vive la experiencia y fuerte estrategia de reels.',
  },
  brand: {
    ...COFFEE_ST_FITZ_CONFIG.brand,
    primaryColor: 'oklch(0.57 0.16 24)',
    accentColor: 'oklch(0.7 0.16 151)',
    bgBase: 'oklch(0.985 0.018 82)',
    darkMode: false,
  },
  theme: {
    ...COFFEE_ST_FITZ_CONFIG.theme!,
    mode: 'light',
    primary: 'oklch(0.57 0.16 24)',
    primaryHover: 'oklch(0.57 0.16 24)',
    accent: 'oklch(0.7 0.16 151)',
    cta: 'oklch(0.77 0.15 82)',
    background: 'oklch(0.985 0.018 82)',
    surface: 'oklch(0.998 0.006 82)',
    surfaceAlt: 'oklch(0.94 0.026 84)',
    border: 'oklch(0.82 0.035 82)',
    text: 'oklch(0.22 0.04 36)',
    textMuted: 'oklch(0.43 0.03 75)',
    radius: 'soft',
    motionIntensity: 'standard',
  },
  seo: {
    title: 'Viva La Brunch - Brunch colorido en Garcia Lavin',
    description: 'Viva La Brunch: Brunch colorido, de terraza y experiencia social, con posicionamiento Vive la experiencia y fuerte estrategia de reels.',
    keywords: ['Viva La Brunch', 'Brunch colorido en Garcia Lavin', 'Plaza Victory, Merida', 'restaurante Merida', 'sitio web restaurante'],
    ogImage: '/assets/og-image.jpg',
    locale: 'es_MX',
    schemaType: 'CafeOrCoffeeShop',
  },
  hero: {
    ...COFFEE_ST_FITZ_CONFIG.hero,
    headline: 'Viva La Brunch\nla manana se celebra',
    subheadline: 'Una pagina alegre y facil de compartir para ordenar menu, terraza, promos y contacto en una experiencia movil mas clara.',
    ctaLabel: 'Ver menu',
    ctaSecondaryLabel: 'Como llegar',
    locationLabel: 'Plaza Victory, Av. Garcia Lavin',
    backgroundImage: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1800&auto=format&fit=crop&q=85',
    overlayOpacity: 0.32,
  },
  cta: {
    reservationLabel: 'Contactar',
    whatsappLabel: 'WhatsApp',
    stickyLabel: 'Ver menu',
  },
  footer: {
    ...COFFEE_ST_FITZ_CONFIG.footer,
    copyrightLabel: 'Viva La Brunch - Plaza Victory, Merida',
  },
  sectionCopy: {
    ...COFFEE_ST_FITZ_CONFIG.sectionCopy,
    images: {
      ...COFFEE_ST_FITZ_CONFIG.sectionCopy.images,
      heroBackground: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1800&auto=format&fit=crop&q=85',
      conceptImage: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=1000&auto=format&fit=crop&q=85',
      conceptImageAlt: 'Viva La Brunch ambiente y propuesta', 
      locationMapImage: 'https://images.unsplash.com/photo-1577086664693-894d8405334a?w=1000&auto=format&fit=crop&q=85',
      menuPageHeroImage: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1600&auto=format&fit=crop&q=85',
      menuItemFallbackImage: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80',
      menuItemImages: {},
    },
    concept: {
      eyebrow: 'El nucleo de la marca',
      heading: 'Una pagina pensada para vender mejor Viva La Brunch',
      lead: 'Viva La Brunch vive de deseo visual: platos abundantes, terraza, color y una comunidad foodie que descubre por reels.',
      body: 'El sitio debe conservar esa energia, pero volverla mas accesible: menu escaneable, ubicacion, horarios y CTA para planear brunch sin perderse en redes.',
      foundedLabel: 'Plaza Victory, Av. Garcia Lavin',
    },
    menuHighlights: {
      eyebrow: 'Favoritos para descubrir',
      heading: 'Brunch colorido en Garcia Lavin',
      subheading: 'Una seleccion breve que convierte el antojo en decision: que pedir, donde esta y como contactar.',
      fullMenuLabel: 'Explorar menu',
    },
    promotions: {
      eyebrow: 'Motivos para ir',
      heading: 'Ganchos comerciales claros para redes, mapa y WhatsApp',
      validUntilPrefix: 'Disponible',
    },
    gallery: {
      eyebrow: 'Primera impresion',
      heading: 'Visuales que explican ambiente, comida y ocasion',
      filters: [
        { id: 'all', label: 'Todo' },
        { id: 'food', label: 'Comida' },
        { id: 'drinks', label: 'Bebidas' },
        { id: 'interior', label: 'Lugar' },
        { id: 'events', label: 'Momentos' },
      ],
    },
    testimonials: {
      eyebrow: 'Prueba social',
      heading: 'Senales que ya existen y el sitio debe ordenar',
      subheading: 'El objetivo es volver accesible lo que hoy vive disperso entre Instagram, mapas, Linktree o sitios de terceros.',
      proofItems: [
        { value: '9.3k', label: 'Seguidores IG' },
        { value: 'Terraza', label: 'Decision rapida' },
        { value: 'Reels', label: 'Alta visibilidad' }
      ],
    },
    location: {
      eyebrow: 'Ubicacion',
      heading: 'Encuentra Viva La Brunch en Plaza Victory, Merida',
    },
    menuPage: {
      eyebrow: 'Menu pensado para movil',
      heading: 'Menu Viva La Brunch',
      lead: 'Categorias claras, platos representativos y llamadas a contacto sin depender de capturas o historias destacadas.',
      finalHeading: 'Listo para visitar Viva La Brunch?',
      finalDescription: 'Menu, mapa, horario y WhatsApp quedan a un toque.',
    },
    contactPage: {
      eyebrow: 'Contacto rapido',
      heading: 'Contacto, ubicacion y reservas',
      whatsappTitle: 'WhatsApp',
      reservationTitle: 'Consulta o reserva',
      reservationDescription: 'Genera un mensaje listo para continuar la conversacion por WhatsApp.',
      emailTitle: 'Contacto',
    },
  },
  menuCategories: [
    { id: 'brunch', name: 'Brunch', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'dulce', name: 'Dulce', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'salado', name: 'Salado', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'cafe', name: 'Cafe', description: 'Seleccion pensada para decidir rapido desde movil' },
    { id: 'bebidas', name: 'Bebidas', description: 'Seleccion pensada para decidir rapido desde movil' }
  ],
  menuItems: [
    { id: 'm1', categoryId: 'brunch', name: 'Pancakes de temporada', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', tag: 'signature', featured: true },
    { id: 'm2', categoryId: 'dulce', name: 'Avocado toast', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm3', categoryId: 'salado', name: 'Chilaquiles brunch', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm4', categoryId: 'cafe', name: 'French toast berries', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145', featured: true },
    { id: 'm5', categoryId: 'bebidas', name: 'Benedictinos de la casa', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm6', categoryId: 'brunch', name: 'Bagel de salmon', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm7', categoryId: 'dulce', name: 'Latte vainilla', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' },
    { id: 'm8', categoryId: 'salado', name: 'Mimosa de terraza', description: 'Una opcion representativa para comunicar la propuesta sin depender solo de redes.', price: '$145' }
  ],
  promotions: [
    { id: 'p1', title: 'Vive la experiencia', description: 'Una razon clara para visitar, reservar o pedir informacion sin buscar en publicaciones.', badge: 'Favorito', ctaLabel: 'Ver menu', ctaAction: 'link', ctaValue: '/menu' },
    { id: 'p2', title: 'Terraza brunch', description: 'Mensaje listo para WhatsApp con horario, personas y dudas principales.', badge: 'Contacto rapido', ctaLabel: 'Escribir', ctaAction: 'whatsapp' }
  ],
  gallery: [
    { id: 'g1', src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1800&auto=format&fit=crop&q=85', alt: 'Viva La Brunch preview image 1', caption: 'Viva La Brunch', category: 'food' },
    { id: 'g2', src: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=1000&auto=format&fit=crop&q=85', alt: 'Viva La Brunch preview image 2', caption: 'Viva La Brunch', category: 'interior' },
    { id: 'g3', src: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1600&auto=format&fit=crop&q=85', alt: 'Viva La Brunch preview image 3', caption: 'Viva La Brunch', category: 'food' },
    { id: 'g4', src: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&auto=format&fit=crop&q=80', alt: 'Viva La Brunch preview image 4', caption: 'Viva La Brunch', category: 'drinks' },
    { id: 'g5', src: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=1800&auto=format&fit=crop&q=85', alt: 'Viva La Brunch preview image 5', caption: 'Viva La Brunch', category: 'events' },
    { id: 'g6', src: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=1000&auto=format&fit=crop&q=85', alt: 'Viva La Brunch preview image 6', caption: 'Viva La Brunch', category: 'interior' }
  ],
  testimonials: [
    { id: 't1', name: 'Audiencia publica', source: 'Instagram', rating: 5, text: 'La marca ya tiene una comunidad de 9.3k seguidores; el sitio convierte esa atencion en acciones.', date: '2026' },
    { id: 't2', name: 'Cliente ideal', source: 'Direct', rating: 5, text: 'La propuesta se entiende rapido: especialidad, ubicacion, menu y contacto sin friccion.', date: '2026' },
    { id: 't3', name: 'Oportunidad digital', source: 'Direct', rating: 5, text: 'Un sitio propio ayuda a depender menos de perfiles sociales y mas de una experiencia controlada.', date: '2026' },
  ],
  faqs: [
    { question: 'Que hace diferente a Viva La Brunch?', answer: 'Brunch colorido, de terraza y experiencia social, con posicionamiento Vive la experiencia y fuerte estrategia de reels.' },
    { question: 'Como contacto o reservo?', answer: 'El sitio prioriza WhatsApp con un mensaje listo para enviar, ademas de mapa y horarios visibles.' },
  ],
  reservation: {
    ...COFFEE_ST_FITZ_CONFIG.reservation,
    modalTitle: 'Contacto rapido Viva La Brunch',
    modalDescription: 'Completa los datos y genera un mensaje listo para WhatsApp.',
    messageTemplate: 'Hola Viva La Brunch. Quisiera informacion o reservar para {{guests}} personas el {{date}} a las {{time}}. Mi nombre es {{name}}. Notas: {{notes}}',
    whatsappNumber: '529990000000',
  },
  whatsapp: {
    number: '529990000000',
    defaultMessage: 'Hola Viva La Brunch, quisiera informacion sobre menu, horario o ubicacion.',
    floatingButton: true,
    ariaLabel: 'Contactar a Viva La Brunch por WhatsApp',
  },
  location: {
    address: 'Plaza Victory, Av. Garcia Lavin',
    city: 'Plaza Victory',
    state: 'Yucatan',
    zip: '97000',
    country: 'Mexico',
    googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=Viva%20La%20Brunch%20Plaza%20Victory%2C%20Merida',
    mapAriaLabel: 'Mapa de ubicacion de Viva La Brunch',
    mapImageAlt: 'Mapa referencial de Viva La Brunch',
    openMapsLabel: 'Abrir ubicacion',
    hoursTitle: 'Horario por confirmar',
    hours: [
      { day: 'Lunes', hours: 'Horario por confirmar' },
      { day: 'Martes', hours: 'Horario por confirmar' },
      { day: 'Miercoles', hours: 'Horario por confirmar' },
      { day: 'Jueves', hours: 'Horario por confirmar' },
      { day: 'Viernes', hours: 'Horario por confirmar' },
      { day: 'Sabado', hours: 'Horario por confirmar' },
      { day: 'Domingo', hours: 'Horario por confirmar' },
    ],
    phone: '+52 999 000 0000',
    email: 'hola@vivalabrunch.mx',
  },
  social: {
    instagram: 'https://www.instagram.com/vivalabrunchmx/',
  },
};

